# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import msgs_control_pb2 as msgs__control__pb2
import msgs_motion_pb2 as msgs__motion__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ControlServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MoveJ = channel.unary_unary(
                '/surrogate.grpc.ControlService/MoveJ',
                request_serializer=msgs__control__pb2.MoveJRequest.SerializeToString,
                response_deserializer=msgs__control__pb2.ControlDefaultReply.FromString,
                _registered_method=True)
        self.SetMobileState = channel.unary_unary(
                '/surrogate.grpc.ControlService/SetMobileState',
                request_serializer=msgs__control__pb2.SetMobileStateRequest.SerializeToString,
                response_deserializer=msgs__motion__pb2.MobileMotionData.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """The greeting service definition.
    """

    def MoveJ(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMobileState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MoveJ': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJ,
                    request_deserializer=msgs__control__pb2.MoveJRequest.FromString,
                    response_serializer=msgs__control__pb2.ControlDefaultReply.SerializeToString,
            ),
            'SetMobileState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMobileState,
                    request_deserializer=msgs__control__pb2.SetMobileStateRequest.FromString,
                    response_serializer=msgs__motion__pb2.MobileMotionData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surrogate.grpc.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surrogate.grpc.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """The greeting service definition.
    """

    @staticmethod
    def MoveJ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surrogate.grpc.ControlService/MoveJ',
            msgs__control__pb2.MoveJRequest.SerializeToString,
            msgs__control__pb2.ControlDefaultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMobileState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surrogate.grpc.ControlService/SetMobileState',
            msgs__control__pb2.SetMobileStateRequest.SerializeToString,
            msgs__motion__pb2.MobileMotionData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
