# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs_config.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msgs_common_pb2 as msgs__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11msgs_config.proto\x12\x0esurrogate.grpc\x1a\x11msgs_common.proto\"\x15\n\x05\x46rame\x12\x0c\n\x04\x66pos\x18\x01 \x03(\x02\"6\n\rFTsensorFrame\x12\x13\n\x0btranslation\x18\x01 \x01(\x02\x12\x10\n\x08rotation\x18\x02 \x01(\x02\"\x18\n\x08JointPos\x12\x0c\n\x04jpos\x18\x01 \x03(\x02\"\x17\n\x07TaskPos\x12\x0c\n\x04tpos\x18\x01 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=56
  _globals['_FRAME']._serialized_end=77
  _globals['_FTSENSORFRAME']._serialized_start=79
  _globals['_FTSENSORFRAME']._serialized_end=133
  _globals['_JOINTPOS']._serialized_start=135
  _globals['_JOINTPOS']._serialized_end=159
  _globals['_TASKPOS']._serialized_start=161
  _globals['_TASKPOS']._serialized_end=184
# @@protoc_insertion_point(module_scope)
