# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11msgs_common.proto\x12\x0esurrogate.grpc\"\x0e\n\x0c\x45mptyRequest\"\x0c\n\nEmptyReply\"=\n\x0c\x44\x65\x66\x61ultReply\x12-\n\ncommand_id\x18\x01 \x01(\x0e\x32\x19.surrogate.grpc.CommandId*i\n\tCommandId\x12\x0c\n\x08\x43MD_NULL\x10\x00\x12\x14\n\x10\x43MD_SYETEM_RESET\x10\x01\x12\x1d\n\x19\x43MD_SYSTEM_EMERGENCY_STOP\x10\x02\x12\x19\n\x15\x43MD_SET_DESIRED_STATE\x10\x64*L\n\x0bSystemState\x12\n\n\x06SS_OFF\x10\x00\x12\t\n\x05SS_ON\x10\x01\x12\x0f\n\x0bSS_RECOVERY\x10\x02\x12\x15\n\x11SS_EMERGENCY_STOP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDID']._serialized_start=130
  _globals['_COMMANDID']._serialized_end=235
  _globals['_SYSTEMSTATE']._serialized_start=237
  _globals['_SYSTEMSTATE']._serialized_end=313
  _globals['_EMPTYREQUEST']._serialized_start=37
  _globals['_EMPTYREQUEST']._serialized_end=51
  _globals['_EMPTYREPLY']._serialized_start=53
  _globals['_EMPTYREPLY']._serialized_end=65
  _globals['_DEFAULTREPLY']._serialized_start=67
  _globals['_DEFAULTREPLY']._serialized_end=128
# @@protoc_insertion_point(module_scope)
