# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs_control.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msgs_common_pb2 as msgs__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12msgs_control.proto\x12\x0esurrogate.grpc\x1a\x11msgs_common.proto\"L\n\x0cMoveJRequest\x12-\n\ncommand_id\x18\x01 \x01(\x0e\x32\x19.surrogate.grpc.CommandId\x12\r\n\x05q_des\x18\x02 \x03(\x02\"L\n\x0cMoveTRequest\x12-\n\ncommand_id\x18\x01 \x01(\x0e\x32\x19.surrogate.grpc.CommandId\x12\r\n\x05p_des\x18\x02 \x03(\x02\"o\n\x15SetMobileStateRequest\x12-\n\ncommand_id\x18\x01 \x01(\x0e\x32\x19.surrogate.grpc.CommandId\x12\x11\n\twheel_vel\x18\x02 \x01(\x02\x12\x14\n\x0csteering_pos\x18\x03 \x01(\x02\"U\n\x13\x43ontrolDefaultReply\x12-\n\ncommand_id\x18\x01 \x01(\x0e\x32\x19.surrogate.grpc.CommandId\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEJREQUEST']._serialized_start=57
  _globals['_MOVEJREQUEST']._serialized_end=133
  _globals['_MOVETREQUEST']._serialized_start=135
  _globals['_MOVETREQUEST']._serialized_end=211
  _globals['_SETMOBILESTATEREQUEST']._serialized_start=213
  _globals['_SETMOBILESTATEREQUEST']._serialized_end=324
  _globals['_CONTROLDEFAULTREPLY']._serialized_start=326
  _globals['_CONTROLDEFAULTREPLY']._serialized_end=411
# @@protoc_insertion_point(module_scope)
