# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs_motion.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msgs_common_pb2 as msgs__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11msgs_motion.proto\x12\x0esurrogate.grpc\x1a\x11msgs_common.proto\"\x1d\n\nMotionData\x12\x0f\n\x07message\x18\x01 \x01(\t\"n\n\x10MobileMotionData\x12\x31\n\x0csystem_state\x18\x01 \x01(\x0e\x32\x1b.surrogate.grpc.SystemState\x12\x11\n\twheel_vel\x18\x02 \x01(\x02\x12\x14\n\x0csteering_pos\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_motion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONDATA']._serialized_start=56
  _globals['_MOTIONDATA']._serialized_end=85
  _globals['_MOBILEMOTIONDATA']._serialized_start=87
  _globals['_MOBILEMOTIONDATA']._serialized_end=197
# @@protoc_insertion_point(module_scope)
