// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_control_2eproto__INCLUDED
#define GRPC_control_2eproto__INCLUDED

#include "control.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace surrogate {
namespace grpc {

// The greeting service definition.
class ControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "surrogate.grpc.ControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::surrogate::grpc::ControlDefaultReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>> AsyncMoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>>(AsyncMoveJRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>> PrepareAsyncMoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>>(PrepareAsyncMoveJRaw(context, request, cq));
    }
    virtual ::grpc::Status SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::surrogate::grpc::MobileMotionData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>> AsyncSetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>>(AsyncSetMobileStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>> PrepareAsyncSetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>>(PrepareAsyncSetMobileStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>* AsyncMoveJRaw(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::ControlDefaultReply>* PrepareAsyncMoveJRaw(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>* AsyncSetMobileStateRaw(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MobileMotionData>* PrepareAsyncSetMobileStateRaw(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::surrogate::grpc::ControlDefaultReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>> AsyncMoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>>(AsyncMoveJRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>> PrepareAsyncMoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>>(PrepareAsyncMoveJRaw(context, request, cq));
    }
    ::grpc::Status SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::surrogate::grpc::MobileMotionData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>> AsyncSetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>>(AsyncSetMobileStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>> PrepareAsyncSetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>>(PrepareAsyncSetMobileStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response, std::function<void(::grpc::Status)>) override;
      void MoveJ(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response, std::function<void(::grpc::Status)>) override;
      void SetMobileState(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>* AsyncMoveJRaw(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::ControlDefaultReply>* PrepareAsyncMoveJRaw(::grpc::ClientContext* context, const ::surrogate::grpc::MoveJRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>* AsyncSetMobileStateRaw(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MobileMotionData>* PrepareAsyncSetMobileStateRaw(::grpc::ClientContext* context, const ::surrogate::grpc::SetMobileStateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MoveJ_;
    const ::grpc::internal::RpcMethod rpcmethod_SetMobileState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status MoveJ(::grpc::ServerContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response);
    virtual ::grpc::Status SetMobileState(::grpc::ServerContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MoveJ() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMoveJ(::grpc::ServerContext* context, ::surrogate::grpc::MoveJRequest* request, ::grpc::ServerAsyncResponseWriter< ::surrogate::grpc::ControlDefaultReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetMobileState() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetMobileState(::grpc::ServerContext* context, ::surrogate::grpc::SetMobileStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::surrogate::grpc::MobileMotionData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MoveJ<WithAsyncMethod_SetMobileState<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MoveJ() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::MoveJRequest, ::surrogate::grpc::ControlDefaultReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surrogate::grpc::MoveJRequest* request, ::surrogate::grpc::ControlDefaultReply* response) { return this->MoveJ(context, request, response); }));}
    void SetMessageAllocatorFor_MoveJ(
        ::grpc::MessageAllocator< ::surrogate::grpc::MoveJRequest, ::surrogate::grpc::ControlDefaultReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::MoveJRequest, ::surrogate::grpc::ControlDefaultReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MoveJ(
      ::grpc::CallbackServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetMobileState() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::SetMobileStateRequest, ::surrogate::grpc::MobileMotionData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surrogate::grpc::SetMobileStateRequest* request, ::surrogate::grpc::MobileMotionData* response) { return this->SetMobileState(context, request, response); }));}
    void SetMessageAllocatorFor_SetMobileState(
        ::grpc::MessageAllocator< ::surrogate::grpc::SetMobileStateRequest, ::surrogate::grpc::MobileMotionData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::SetMobileStateRequest, ::surrogate::grpc::MobileMotionData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetMobileState(
      ::grpc::CallbackServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_MoveJ<WithCallbackMethod_SetMobileState<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MoveJ() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetMobileState() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MoveJ() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMoveJ(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetMobileState() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetMobileState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MoveJ() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MoveJ(context, request, response); }));
    }
    ~WithRawCallbackMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MoveJ(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetMobileState() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetMobileState(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetMobileState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MoveJ : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MoveJ() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surrogate::grpc::MoveJRequest, ::surrogate::grpc::ControlDefaultReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surrogate::grpc::MoveJRequest, ::surrogate::grpc::ControlDefaultReply>* streamer) {
                       return this->StreamedMoveJ(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MoveJ() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MoveJ(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::MoveJRequest* /*request*/, ::surrogate::grpc::ControlDefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMoveJ(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surrogate::grpc::MoveJRequest,::surrogate::grpc::ControlDefaultReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetMobileState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetMobileState() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surrogate::grpc::SetMobileStateRequest, ::surrogate::grpc::MobileMotionData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surrogate::grpc::SetMobileStateRequest, ::surrogate::grpc::MobileMotionData>* streamer) {
                       return this->StreamedSetMobileState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetMobileState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetMobileState(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::SetMobileStateRequest* /*request*/, ::surrogate::grpc::MobileMotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetMobileState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surrogate::grpc::SetMobileStateRequest,::surrogate::grpc::MobileMotionData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MoveJ<WithStreamedUnaryMethod_SetMobileState<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MoveJ<WithStreamedUnaryMethod_SetMobileState<Service > > StreamedService;
};

}  // namespace grpc
}  // namespace surrogate


#endif  // GRPC_control_2eproto__INCLUDED
