// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: motion.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_motion_2eproto__INCLUDED
#define GRPC_motion_2eproto__INCLUDED

#include "motion.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace surrogate {
namespace grpc {

// The greeting service definition.
class MotionService final {
 public:
  static constexpr char const* service_full_name() {
    return "surrogate.grpc.MotionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::surrogate::grpc::MotionData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>> AsyncGetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>>(AsyncGetMotionDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>> PrepareAsyncGetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>>(PrepareAsyncGetMotionDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>* AsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surrogate::grpc::MotionData>* PrepareAsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::surrogate::grpc::MotionData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>> AsyncGetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>>(AsyncGetMotionDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>> PrepareAsyncGetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>>(PrepareAsyncGetMotionDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, std::function<void(::grpc::Status)>) override;
      void GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>* AsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>* PrepareAsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMotionData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status GetMotionData(::grpc::ServerContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMotionData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMotionData(::grpc::ServerContext* context, ::surrogate::grpc::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::surrogate::grpc::MotionData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMotionData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMotionData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response) { return this->GetMotionData(context, request, response); }));}
    void SetMessageAllocatorFor_GetMotionData(
        ::grpc::MessageAllocator< ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMotionData(
      ::grpc::CallbackServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetMotionData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMotionData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMotionData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMotionData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMotionData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMotionData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMotionData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMotionData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMotionData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData>* streamer) {
                       return this->StreamedGetMotionData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMotionData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMotionData(::grpc::ServerContext* /*context*/, const ::surrogate::grpc::EmptyRequest* /*request*/, ::surrogate::grpc::MotionData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMotionData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surrogate::grpc::EmptyRequest,::surrogate::grpc::MotionData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMotionData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMotionData<Service > StreamedService;
};

}  // namespace grpc
}  // namespace surrogate


#endif  // GRPC_motion_2eproto__INCLUDED
