// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: motion.proto

#include "motion.pb.h"
#include "motion.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace surrogate {
namespace grpc {

static const char* MotionService_method_names[] = {
  "/surrogate.grpc.MotionService/GetMotionData",
};

std::unique_ptr< MotionService::Stub> MotionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MotionService::Stub> stub(new MotionService::Stub(channel, options));
  return stub;
}

MotionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMotionData_(MotionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MotionService::Stub::GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::surrogate::grpc::MotionData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMotionData_, context, request, response);
}

void MotionService::Stub::async::GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMotionData_, context, request, response, std::move(f));
}

void MotionService::Stub::async::GetMotionData(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMotionData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>* MotionService::Stub::PrepareAsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surrogate::grpc::MotionData, ::surrogate::grpc::EmptyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMotionData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::MotionData>* MotionService::Stub::AsyncGetMotionDataRaw(::grpc::ClientContext* context, const ::surrogate::grpc::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMotionDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

MotionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MotionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MotionService::Service, ::surrogate::grpc::EmptyRequest, ::surrogate::grpc::MotionData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MotionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surrogate::grpc::EmptyRequest* req,
             ::surrogate::grpc::MotionData* resp) {
               return service->GetMotionData(ctx, req, resp);
             }, this)));
}

MotionService::Service::~Service() {
}

::grpc::Status MotionService::Service::GetMotionData(::grpc::ServerContext* context, const ::surrogate::grpc::EmptyRequest* request, ::surrogate::grpc::MotionData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace surrogate
}  // namespace grpc

