// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_config.proto
// Protobuf C++ Version: 5.26.1

#include "msgs_config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace surrogate {
namespace grpc {

inline constexpr TaskPos::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tpos_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskPos::TaskPos(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TaskPosDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskPosDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskPosDefaultTypeInternal() {}
  union {
    TaskPos _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskPosDefaultTypeInternal _TaskPos_default_instance_;

inline constexpr JointPos::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : jpos_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JointPos::JointPos(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JointPosDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointPosDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointPosDefaultTypeInternal() {}
  union {
    JointPos _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointPosDefaultTypeInternal _JointPos_default_instance_;

inline constexpr Frame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : fpos_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Frame::Frame(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameDefaultTypeInternal() {}
  union {
    Frame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameDefaultTypeInternal _Frame_default_instance_;

inline constexpr FTsensorFrame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : translation_{0},
        rotation_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FTsensorFrame::FTsensorFrame(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FTsensorFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FTsensorFrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FTsensorFrameDefaultTypeInternal() {}
  union {
    FTsensorFrame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FTsensorFrameDefaultTypeInternal _FTsensorFrame_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fconfig_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msgs_5fconfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msgs_5fconfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_msgs_5fconfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::Frame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::Frame, _impl_.fpos_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::FTsensorFrame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::FTsensorFrame, _impl_.translation_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::FTsensorFrame, _impl_.rotation_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::JointPos, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::JointPos, _impl_.jpos_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::TaskPos, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::TaskPos, _impl_.tpos_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::surrogate::grpc::Frame)},
        {9, -1, -1, sizeof(::surrogate::grpc::FTsensorFrame)},
        {19, -1, -1, sizeof(::surrogate::grpc::JointPos)},
        {28, -1, -1, sizeof(::surrogate::grpc::TaskPos)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::surrogate::grpc::_Frame_default_instance_._instance,
    &::surrogate::grpc::_FTsensorFrame_default_instance_._instance,
    &::surrogate::grpc::_JointPos_default_instance_._instance,
    &::surrogate::grpc::_TaskPos_default_instance_._instance,
};
const char descriptor_table_protodef_msgs_5fconfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021msgs_config.proto\022\016surrogate.grpc\032\021msg"
    "s_common.proto\"\025\n\005Frame\022\014\n\004fpos\030\001 \003(\002\"6\n"
    "\rFTsensorFrame\022\023\n\013translation\030\001 \001(\002\022\020\n\010r"
    "otation\030\002 \001(\002\"\030\n\010JointPos\022\014\n\004jpos\030\001 \003(\002\""
    "\027\n\007TaskPos\022\014\n\004tpos\030\001 \003(\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msgs_5fconfig_2eproto_deps[1] =
    {
        &::descriptor_table_msgs_5fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_msgs_5fconfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fconfig_2eproto = {
    false,
    false,
    192,
    descriptor_table_protodef_msgs_5fconfig_2eproto,
    "msgs_config.proto",
    &descriptor_table_msgs_5fconfig_2eproto_once,
    descriptor_table_msgs_5fconfig_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_msgs_5fconfig_2eproto::offsets,
    file_level_metadata_msgs_5fconfig_2eproto,
    file_level_enum_descriptors_msgs_5fconfig_2eproto,
    file_level_service_descriptors_msgs_5fconfig_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fconfig_2eproto_getter() {
  return &descriptor_table_msgs_5fconfig_2eproto;
}
namespace surrogate {
namespace grpc {
// ===================================================================

class Frame::_Internal {
 public:
};

Frame::Frame(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.Frame)
}
inline PROTOBUF_NDEBUG_INLINE Frame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : fpos_{visibility, arena, from.fpos_},
        _cached_size_{0} {}

Frame::Frame(
    ::google::protobuf::Arena* arena,
    const Frame& from)
    : ::google::protobuf::Message(arena) {
  Frame* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.Frame)
}
inline PROTOBUF_NDEBUG_INLINE Frame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : fpos_{visibility, arena},
        _cached_size_{0} {}

inline void Frame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Frame::~Frame() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.Frame)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Frame::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Frame::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Frame, _impl_._cached_size_),
              false,
          },
          &Frame::MergeImpl,
          &Frame::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Frame::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.Frame)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fpos_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Frame::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Frame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Frame_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::Frame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float fpos = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Frame, _impl_.fpos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float fpos = 1;
    {PROTOBUF_FIELD_OFFSET(Frame, _impl_.fpos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Frame::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.Frame)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float fpos = 1;
  if (this->_internal_fpos_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_fpos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.Frame)
  return target;
}

::size_t Frame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.Frame)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float fpos = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_fpos_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Frame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Frame*>(&to_msg);
  auto& from = static_cast<const Frame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.Frame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_fpos()->MergeFrom(from._internal_fpos());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Frame::CopyFrom(const Frame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.Frame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Frame::IsInitialized() const {
  return true;
}

void Frame::InternalSwap(Frame* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fpos_.InternalSwap(&other->_impl_.fpos_);
}

::google::protobuf::Metadata Frame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fconfig_2eproto_getter,
                                   &descriptor_table_msgs_5fconfig_2eproto_once,
                                   file_level_metadata_msgs_5fconfig_2eproto[0]);
}
// ===================================================================

class FTsensorFrame::_Internal {
 public:
};

FTsensorFrame::FTsensorFrame(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.FTsensorFrame)
}
FTsensorFrame::FTsensorFrame(
    ::google::protobuf::Arena* arena, const FTsensorFrame& from)
    : FTsensorFrame(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FTsensorFrame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FTsensorFrame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, translation_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, translation_) +
               sizeof(Impl_::rotation_));
}
FTsensorFrame::~FTsensorFrame() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.FTsensorFrame)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FTsensorFrame::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FTsensorFrame::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_._cached_size_),
              false,
          },
          &FTsensorFrame::MergeImpl,
          &FTsensorFrame::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void FTsensorFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.FTsensorFrame)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.translation_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rotation_) -
      reinterpret_cast<char*>(&_impl_.translation_)) + sizeof(_impl_.rotation_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FTsensorFrame::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> FTsensorFrame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FTsensorFrame_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::FTsensorFrame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float rotation = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.rotation_)}},
    // float translation = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.translation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float translation = 1;
    {PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.translation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float rotation = 2;
    {PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.rotation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FTsensorFrame::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.FTsensorFrame)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float translation = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_translation = this->_internal_translation();
  ::uint32_t raw_translation;
  memcpy(&raw_translation, &tmp_translation, sizeof(tmp_translation));
  if (raw_translation != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_translation(), target);
  }

  // float rotation = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rotation = this->_internal_rotation();
  ::uint32_t raw_rotation;
  memcpy(&raw_rotation, &tmp_rotation, sizeof(tmp_rotation));
  if (raw_rotation != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_rotation(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.FTsensorFrame)
  return target;
}

::size_t FTsensorFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.FTsensorFrame)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float translation = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_translation = this->_internal_translation();
  ::uint32_t raw_translation;
  memcpy(&raw_translation, &tmp_translation, sizeof(tmp_translation));
  if (raw_translation != 0) {
    total_size += 5;
  }

  // float rotation = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rotation = this->_internal_rotation();
  ::uint32_t raw_rotation;
  memcpy(&raw_rotation, &tmp_rotation, sizeof(tmp_rotation));
  if (raw_rotation != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void FTsensorFrame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FTsensorFrame*>(&to_msg);
  auto& from = static_cast<const FTsensorFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.FTsensorFrame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_translation = from._internal_translation();
  ::uint32_t raw_translation;
  memcpy(&raw_translation, &tmp_translation, sizeof(tmp_translation));
  if (raw_translation != 0) {
    _this->_impl_.translation_ = from._impl_.translation_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rotation = from._internal_rotation();
  ::uint32_t raw_rotation;
  memcpy(&raw_rotation, &tmp_rotation, sizeof(tmp_rotation));
  if (raw_rotation != 0) {
    _this->_impl_.rotation_ = from._impl_.rotation_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FTsensorFrame::CopyFrom(const FTsensorFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.FTsensorFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FTsensorFrame::IsInitialized() const {
  return true;
}

void FTsensorFrame::InternalSwap(FTsensorFrame* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.rotation_)
      + sizeof(FTsensorFrame::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(FTsensorFrame, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::google::protobuf::Metadata FTsensorFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fconfig_2eproto_getter,
                                   &descriptor_table_msgs_5fconfig_2eproto_once,
                                   file_level_metadata_msgs_5fconfig_2eproto[1]);
}
// ===================================================================

class JointPos::_Internal {
 public:
};

JointPos::JointPos(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.JointPos)
}
inline PROTOBUF_NDEBUG_INLINE JointPos::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : jpos_{visibility, arena, from.jpos_},
        _cached_size_{0} {}

JointPos::JointPos(
    ::google::protobuf::Arena* arena,
    const JointPos& from)
    : ::google::protobuf::Message(arena) {
  JointPos* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.JointPos)
}
inline PROTOBUF_NDEBUG_INLINE JointPos::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : jpos_{visibility, arena},
        _cached_size_{0} {}

inline void JointPos::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
JointPos::~JointPos() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.JointPos)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JointPos::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
JointPos::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(JointPos, _impl_._cached_size_),
              false,
          },
          &JointPos::MergeImpl,
          &JointPos::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void JointPos::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.JointPos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.jpos_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JointPos::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> JointPos::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_JointPos_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::JointPos>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float jpos = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(JointPos, _impl_.jpos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float jpos = 1;
    {PROTOBUF_FIELD_OFFSET(JointPos, _impl_.jpos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* JointPos::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.JointPos)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float jpos = 1;
  if (this->_internal_jpos_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_jpos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.JointPos)
  return target;
}

::size_t JointPos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.JointPos)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float jpos = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_jpos_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void JointPos::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JointPos*>(&to_msg);
  auto& from = static_cast<const JointPos&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.JointPos)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_jpos()->MergeFrom(from._internal_jpos());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JointPos::CopyFrom(const JointPos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.JointPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JointPos::IsInitialized() const {
  return true;
}

void JointPos::InternalSwap(JointPos* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.jpos_.InternalSwap(&other->_impl_.jpos_);
}

::google::protobuf::Metadata JointPos::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fconfig_2eproto_getter,
                                   &descriptor_table_msgs_5fconfig_2eproto_once,
                                   file_level_metadata_msgs_5fconfig_2eproto[2]);
}
// ===================================================================

class TaskPos::_Internal {
 public:
};

TaskPos::TaskPos(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.TaskPos)
}
inline PROTOBUF_NDEBUG_INLINE TaskPos::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : tpos_{visibility, arena, from.tpos_},
        _cached_size_{0} {}

TaskPos::TaskPos(
    ::google::protobuf::Arena* arena,
    const TaskPos& from)
    : ::google::protobuf::Message(arena) {
  TaskPos* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.TaskPos)
}
inline PROTOBUF_NDEBUG_INLINE TaskPos::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : tpos_{visibility, arena},
        _cached_size_{0} {}

inline void TaskPos::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TaskPos::~TaskPos() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.TaskPos)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TaskPos::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
TaskPos::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(TaskPos, _impl_._cached_size_),
              false,
          },
          &TaskPos::MergeImpl,
          &TaskPos::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void TaskPos::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.TaskPos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tpos_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TaskPos::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> TaskPos::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TaskPos_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::TaskPos>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float tpos = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TaskPos, _impl_.tpos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float tpos = 1;
    {PROTOBUF_FIELD_OFFSET(TaskPos, _impl_.tpos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* TaskPos::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.TaskPos)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float tpos = 1;
  if (this->_internal_tpos_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_tpos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.TaskPos)
  return target;
}

::size_t TaskPos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.TaskPos)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float tpos = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tpos_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void TaskPos::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskPos*>(&to_msg);
  auto& from = static_cast<const TaskPos&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.TaskPos)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_tpos()->MergeFrom(from._internal_tpos());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskPos::CopyFrom(const TaskPos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.TaskPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TaskPos::IsInitialized() const {
  return true;
}

void TaskPos::InternalSwap(TaskPos* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tpos_.InternalSwap(&other->_impl_.tpos_);
}

::google::protobuf::Metadata TaskPos::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fconfig_2eproto_getter,
                                   &descriptor_table_msgs_5fconfig_2eproto_once,
                                   file_level_metadata_msgs_5fconfig_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_msgs_5fconfig_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
