// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_control.proto
// Protobuf C++ Version: 5.26.1

#include "msgs_control.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace surrogate {
namespace grpc {

inline constexpr SetMobileStateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        wheel_vel_{0},
        steering_pos_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetMobileStateRequest::SetMobileStateRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SetMobileStateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetMobileStateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetMobileStateRequestDefaultTypeInternal() {}
  union {
    SetMobileStateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetMobileStateRequestDefaultTypeInternal _SetMobileStateRequest_default_instance_;

inline constexpr MoveTRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : p_des_{},
        command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MoveTRequest::MoveTRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MoveTRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MoveTRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MoveTRequestDefaultTypeInternal() {}
  union {
    MoveTRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MoveTRequestDefaultTypeInternal _MoveTRequest_default_instance_;

inline constexpr MoveJRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : q_des_{},
        command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MoveJRequest::MoveJRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MoveJRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MoveJRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MoveJRequestDefaultTypeInternal() {}
  union {
    MoveJRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MoveJRequestDefaultTypeInternal _MoveJRequest_default_instance_;

inline constexpr ControlDefaultReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ControlDefaultReply::ControlDefaultReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ControlDefaultReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ControlDefaultReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ControlDefaultReplyDefaultTypeInternal() {}
  union {
    ControlDefaultReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ControlDefaultReplyDefaultTypeInternal _ControlDefaultReply_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fcontrol_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msgs_5fcontrol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msgs_5fcontrol_2eproto = nullptr;
const ::uint32_t
    TableStruct_msgs_5fcontrol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveJRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveJRequest, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveJRequest, _impl_.q_des_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveTRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveTRequest, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MoveTRequest, _impl_.p_des_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SetMobileStateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SetMobileStateRequest, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SetMobileStateRequest, _impl_.wheel_vel_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SetMobileStateRequest, _impl_.steering_pos_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ControlDefaultReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ControlDefaultReply, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ControlDefaultReply, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::surrogate::grpc::MoveJRequest)},
        {10, -1, -1, sizeof(::surrogate::grpc::MoveTRequest)},
        {20, -1, -1, sizeof(::surrogate::grpc::SetMobileStateRequest)},
        {31, -1, -1, sizeof(::surrogate::grpc::ControlDefaultReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::surrogate::grpc::_MoveJRequest_default_instance_._instance,
    &::surrogate::grpc::_MoveTRequest_default_instance_._instance,
    &::surrogate::grpc::_SetMobileStateRequest_default_instance_._instance,
    &::surrogate::grpc::_ControlDefaultReply_default_instance_._instance,
};
const char descriptor_table_protodef_msgs_5fcontrol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022msgs_control.proto\022\016surrogate.grpc\032\021ms"
    "gs_common.proto\"L\n\014MoveJRequest\022-\n\ncomma"
    "nd_id\030\001 \001(\0162\031.surrogate.grpc.CommandId\022\r"
    "\n\005q_des\030\002 \003(\002\"L\n\014MoveTRequest\022-\n\ncommand"
    "_id\030\001 \001(\0162\031.surrogate.grpc.CommandId\022\r\n\005"
    "p_des\030\002 \003(\002\"o\n\025SetMobileStateRequest\022-\n\n"
    "command_id\030\001 \001(\0162\031.surrogate.grpc.Comman"
    "dId\022\021\n\twheel_vel\030\002 \001(\002\022\024\n\014steering_pos\030\003"
    " \001(\002\"U\n\023ControlDefaultReply\022-\n\ncommand_i"
    "d\030\001 \001(\0162\031.surrogate.grpc.CommandId\022\017\n\007me"
    "ssage\030\002 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msgs_5fcontrol_2eproto_deps[1] =
    {
        &::descriptor_table_msgs_5fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_msgs_5fcontrol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fcontrol_2eproto = {
    false,
    false,
    419,
    descriptor_table_protodef_msgs_5fcontrol_2eproto,
    "msgs_control.proto",
    &descriptor_table_msgs_5fcontrol_2eproto_once,
    descriptor_table_msgs_5fcontrol_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_msgs_5fcontrol_2eproto::offsets,
    file_level_metadata_msgs_5fcontrol_2eproto,
    file_level_enum_descriptors_msgs_5fcontrol_2eproto,
    file_level_service_descriptors_msgs_5fcontrol_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fcontrol_2eproto_getter() {
  return &descriptor_table_msgs_5fcontrol_2eproto;
}
namespace surrogate {
namespace grpc {
// ===================================================================

class MoveJRequest::_Internal {
 public:
};

MoveJRequest::MoveJRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.MoveJRequest)
}
inline PROTOBUF_NDEBUG_INLINE MoveJRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : q_des_{visibility, arena, from.q_des_},
        _cached_size_{0} {}

MoveJRequest::MoveJRequest(
    ::google::protobuf::Arena* arena,
    const MoveJRequest& from)
    : ::google::protobuf::Message(arena) {
  MoveJRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.command_id_ = from._impl_.command_id_;

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.MoveJRequest)
}
inline PROTOBUF_NDEBUG_INLINE MoveJRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : q_des_{visibility, arena},
        _cached_size_{0} {}

inline void MoveJRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.command_id_ = {};
}
MoveJRequest::~MoveJRequest() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.MoveJRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MoveJRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MoveJRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(MoveJRequest, _impl_._cached_size_),
              false,
          },
          &MoveJRequest::MergeImpl,
          &MoveJRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void MoveJRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.MoveJRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.q_des_.Clear();
  _impl_.command_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MoveJRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MoveJRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MoveJRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::MoveJRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float q_des = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MoveJRequest, _impl_.q_des_)}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MoveJRequest, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MoveJRequest, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(MoveJRequest, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated float q_des = 2;
    {PROTOBUF_FIELD_OFFSET(MoveJRequest, _impl_.q_des_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* MoveJRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.MoveJRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // repeated float q_des = 2;
  if (this->_internal_q_des_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_q_des(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.MoveJRequest)
  return target;
}

::size_t MoveJRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.MoveJRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float q_des = 2;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_q_des_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MoveJRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MoveJRequest*>(&to_msg);
  auto& from = static_cast<const MoveJRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.MoveJRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_q_des()->MergeFrom(from._internal_q_des());
  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MoveJRequest::CopyFrom(const MoveJRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.MoveJRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MoveJRequest::IsInitialized() const {
  return true;
}

void MoveJRequest::InternalSwap(MoveJRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.q_des_.InternalSwap(&other->_impl_.q_des_);
  swap(_impl_.command_id_, other->_impl_.command_id_);
}

::google::protobuf::Metadata MoveJRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcontrol_2eproto_getter,
                                   &descriptor_table_msgs_5fcontrol_2eproto_once,
                                   file_level_metadata_msgs_5fcontrol_2eproto[0]);
}
// ===================================================================

class MoveTRequest::_Internal {
 public:
};

MoveTRequest::MoveTRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.MoveTRequest)
}
inline PROTOBUF_NDEBUG_INLINE MoveTRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : p_des_{visibility, arena, from.p_des_},
        _cached_size_{0} {}

MoveTRequest::MoveTRequest(
    ::google::protobuf::Arena* arena,
    const MoveTRequest& from)
    : ::google::protobuf::Message(arena) {
  MoveTRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.command_id_ = from._impl_.command_id_;

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.MoveTRequest)
}
inline PROTOBUF_NDEBUG_INLINE MoveTRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : p_des_{visibility, arena},
        _cached_size_{0} {}

inline void MoveTRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.command_id_ = {};
}
MoveTRequest::~MoveTRequest() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.MoveTRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MoveTRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MoveTRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(MoveTRequest, _impl_._cached_size_),
              false,
          },
          &MoveTRequest::MergeImpl,
          &MoveTRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void MoveTRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.MoveTRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.p_des_.Clear();
  _impl_.command_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MoveTRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MoveTRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MoveTRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::MoveTRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float p_des = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MoveTRequest, _impl_.p_des_)}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MoveTRequest, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MoveTRequest, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(MoveTRequest, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated float p_des = 2;
    {PROTOBUF_FIELD_OFFSET(MoveTRequest, _impl_.p_des_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* MoveTRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.MoveTRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // repeated float p_des = 2;
  if (this->_internal_p_des_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_p_des(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.MoveTRequest)
  return target;
}

::size_t MoveTRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.MoveTRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float p_des = 2;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_p_des_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MoveTRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MoveTRequest*>(&to_msg);
  auto& from = static_cast<const MoveTRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.MoveTRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_p_des()->MergeFrom(from._internal_p_des());
  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MoveTRequest::CopyFrom(const MoveTRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.MoveTRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MoveTRequest::IsInitialized() const {
  return true;
}

void MoveTRequest::InternalSwap(MoveTRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.p_des_.InternalSwap(&other->_impl_.p_des_);
  swap(_impl_.command_id_, other->_impl_.command_id_);
}

::google::protobuf::Metadata MoveTRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcontrol_2eproto_getter,
                                   &descriptor_table_msgs_5fcontrol_2eproto_once,
                                   file_level_metadata_msgs_5fcontrol_2eproto[1]);
}
// ===================================================================

class SetMobileStateRequest::_Internal {
 public:
};

SetMobileStateRequest::SetMobileStateRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.SetMobileStateRequest)
}
SetMobileStateRequest::SetMobileStateRequest(
    ::google::protobuf::Arena* arena, const SetMobileStateRequest& from)
    : SetMobileStateRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SetMobileStateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SetMobileStateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           0,
           offsetof(Impl_, steering_pos_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::steering_pos_));
}
SetMobileStateRequest::~SetMobileStateRequest() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.SetMobileStateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SetMobileStateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SetMobileStateRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_._cached_size_),
              false,
          },
          &SetMobileStateRequest::MergeImpl,
          &SetMobileStateRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void SetMobileStateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.SetMobileStateRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.steering_pos_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.steering_pos_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SetMobileStateRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> SetMobileStateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SetMobileStateRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::SetMobileStateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SetMobileStateRequest, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.command_id_)}},
    // float wheel_vel = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.wheel_vel_)}},
    // float steering_pos = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.steering_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // float wheel_vel = 2;
    {PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.wheel_vel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float steering_pos = 3;
    {PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.steering_pos_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* SetMobileStateRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.SetMobileStateRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // float wheel_vel = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = this->_internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_wheel_vel(), target);
  }

  // float steering_pos = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = this->_internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_steering_pos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.SetMobileStateRequest)
  return target;
}

::size_t SetMobileStateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.SetMobileStateRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  // float wheel_vel = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = this->_internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    total_size += 5;
  }

  // float steering_pos = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = this->_internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SetMobileStateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetMobileStateRequest*>(&to_msg);
  auto& from = static_cast<const SetMobileStateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.SetMobileStateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = from._internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    _this->_impl_.wheel_vel_ = from._impl_.wheel_vel_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = from._internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    _this->_impl_.steering_pos_ = from._impl_.steering_pos_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetMobileStateRequest::CopyFrom(const SetMobileStateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.SetMobileStateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SetMobileStateRequest::IsInitialized() const {
  return true;
}

void SetMobileStateRequest::InternalSwap(SetMobileStateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.steering_pos_)
      + sizeof(SetMobileStateRequest::_impl_.steering_pos_)
      - PROTOBUF_FIELD_OFFSET(SetMobileStateRequest, _impl_.command_id_)>(
          reinterpret_cast<char*>(&_impl_.command_id_),
          reinterpret_cast<char*>(&other->_impl_.command_id_));
}

::google::protobuf::Metadata SetMobileStateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcontrol_2eproto_getter,
                                   &descriptor_table_msgs_5fcontrol_2eproto_once,
                                   file_level_metadata_msgs_5fcontrol_2eproto[2]);
}
// ===================================================================

class ControlDefaultReply::_Internal {
 public:
};

ControlDefaultReply::ControlDefaultReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.ControlDefaultReply)
}
inline PROTOBUF_NDEBUG_INLINE ControlDefaultReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ControlDefaultReply::ControlDefaultReply(
    ::google::protobuf::Arena* arena,
    const ControlDefaultReply& from)
    : ::google::protobuf::Message(arena) {
  ControlDefaultReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.command_id_ = from._impl_.command_id_;

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.ControlDefaultReply)
}
inline PROTOBUF_NDEBUG_INLINE ControlDefaultReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ControlDefaultReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.command_id_ = {};
}
ControlDefaultReply::~ControlDefaultReply() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.ControlDefaultReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ControlDefaultReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ControlDefaultReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ControlDefaultReply, _impl_._cached_size_),
              false,
          },
          &ControlDefaultReply::MergeImpl,
          &ControlDefaultReply::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ControlDefaultReply::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.ControlDefaultReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.command_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ControlDefaultReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2> ControlDefaultReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ControlDefaultReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::ControlDefaultReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ControlDefaultReply, _impl_.message_)}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ControlDefaultReply, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ControlDefaultReply, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(ControlDefaultReply, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(ControlDefaultReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\7\0\0\0\0\0"
    "surrogate.grpc.ControlDefaultReply"
    "message"
  }},
};

::uint8_t* ControlDefaultReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.ControlDefaultReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "surrogate.grpc.ControlDefaultReply.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.ControlDefaultReply)
  return target;
}

::size_t ControlDefaultReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.ControlDefaultReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ControlDefaultReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ControlDefaultReply*>(&to_msg);
  auto& from = static_cast<const ControlDefaultReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.ControlDefaultReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ControlDefaultReply::CopyFrom(const ControlDefaultReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.ControlDefaultReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ControlDefaultReply::IsInitialized() const {
  return true;
}

void ControlDefaultReply::InternalSwap(ControlDefaultReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.command_id_, other->_impl_.command_id_);
}

::google::protobuf::Metadata ControlDefaultReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcontrol_2eproto_getter,
                                   &descriptor_table_msgs_5fcontrol_2eproto_once,
                                   file_level_metadata_msgs_5fcontrol_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_msgs_5fcontrol_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
