// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_system.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msgs_5fsystem_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msgs_5fsystem_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "msgs_common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msgs_5fsystem_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msgs_5fsystem_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msgs_5fsystem_2eproto;
namespace surrogate {
namespace grpc {
class ChangeSystemStateRequest;
struct ChangeSystemStateRequestDefaultTypeInternal;
extern ChangeSystemStateRequestDefaultTypeInternal _ChangeSystemStateRequest_default_instance_;
class SystemStateReply;
struct SystemStateReplyDefaultTypeInternal;
extern SystemStateReplyDefaultTypeInternal _SystemStateReply_default_instance_;
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace surrogate {
namespace grpc {

// ===================================================================


// -------------------------------------------------------------------

class SystemStateReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.SystemStateReply) */ {
 public:
  inline SystemStateReply() : SystemStateReply(nullptr) {}
  ~SystemStateReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SystemStateReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline SystemStateReply(const SystemStateReply& from) : SystemStateReply(nullptr, from) {}
  inline SystemStateReply(SystemStateReply&& from) noexcept
      : SystemStateReply(nullptr, std::move(from)) {}
  inline SystemStateReply& operator=(const SystemStateReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SystemStateReply& operator=(SystemStateReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SystemStateReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const SystemStateReply* internal_default_instance() {
    return reinterpret_cast<const SystemStateReply*>(
        &_SystemStateReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SystemStateReply& a, SystemStateReply& b) { a.Swap(&b); }
  inline void Swap(SystemStateReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SystemStateReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SystemStateReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<SystemStateReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SystemStateReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SystemStateReply& from) { SystemStateReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SystemStateReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.SystemStateReply"; }

 protected:
  explicit SystemStateReply(::google::protobuf::Arena* arena);
  SystemStateReply(::google::protobuf::Arena* arena, const SystemStateReply& from);
  SystemStateReply(::google::protobuf::Arena* arena, SystemStateReply&& from) noexcept
      : SystemStateReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandIdFieldNumber = 1,
    kSystemStateFieldNumber = 2,
  };
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // .surrogate.grpc.SystemState system_state = 2;
  void clear_system_state() ;
  ::surrogate::grpc::SystemState system_state() const;
  void set_system_state(::surrogate::grpc::SystemState value);

  private:
  ::surrogate::grpc::SystemState _internal_system_state() const;
  void _internal_set_system_state(::surrogate::grpc::SystemState value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.SystemStateReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    int command_id_;
    int system_state_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fsystem_2eproto;
};
// -------------------------------------------------------------------

class ChangeSystemStateRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.ChangeSystemStateRequest) */ {
 public:
  inline ChangeSystemStateRequest() : ChangeSystemStateRequest(nullptr) {}
  ~ChangeSystemStateRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChangeSystemStateRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ChangeSystemStateRequest(const ChangeSystemStateRequest& from) : ChangeSystemStateRequest(nullptr, from) {}
  inline ChangeSystemStateRequest(ChangeSystemStateRequest&& from) noexcept
      : ChangeSystemStateRequest(nullptr, std::move(from)) {}
  inline ChangeSystemStateRequest& operator=(const ChangeSystemStateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChangeSystemStateRequest& operator=(ChangeSystemStateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChangeSystemStateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChangeSystemStateRequest* internal_default_instance() {
    return reinterpret_cast<const ChangeSystemStateRequest*>(
        &_ChangeSystemStateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ChangeSystemStateRequest& a, ChangeSystemStateRequest& b) { a.Swap(&b); }
  inline void Swap(ChangeSystemStateRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChangeSystemStateRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChangeSystemStateRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ChangeSystemStateRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChangeSystemStateRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChangeSystemStateRequest& from) { ChangeSystemStateRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ChangeSystemStateRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.ChangeSystemStateRequest"; }

 protected:
  explicit ChangeSystemStateRequest(::google::protobuf::Arena* arena);
  ChangeSystemStateRequest(::google::protobuf::Arena* arena, const ChangeSystemStateRequest& from);
  ChangeSystemStateRequest(::google::protobuf::Arena* arena, ChangeSystemStateRequest&& from) noexcept
      : ChangeSystemStateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandIdFieldNumber = 1,
    kSystemStateFieldNumber = 2,
  };
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // .surrogate.grpc.SystemState system_state = 2;
  void clear_system_state() ;
  ::surrogate::grpc::SystemState system_state() const;
  void set_system_state(::surrogate::grpc::SystemState value);

  private:
  ::surrogate::grpc::SystemState _internal_system_state() const;
  void _internal_set_system_state(::surrogate::grpc::SystemState value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.ChangeSystemStateRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    int command_id_;
    int system_state_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fsystem_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ChangeSystemStateRequest

// .surrogate.grpc.CommandId command_id = 1;
inline void ChangeSystemStateRequest::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId ChangeSystemStateRequest::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.ChangeSystemStateRequest.command_id)
  return _internal_command_id();
}
inline void ChangeSystemStateRequest::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.ChangeSystemStateRequest.command_id)
}
inline ::surrogate::grpc::CommandId ChangeSystemStateRequest::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void ChangeSystemStateRequest::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// .surrogate.grpc.SystemState system_state = 2;
inline void ChangeSystemStateRequest::clear_system_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.system_state_ = 0;
}
inline ::surrogate::grpc::SystemState ChangeSystemStateRequest::system_state() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.ChangeSystemStateRequest.system_state)
  return _internal_system_state();
}
inline void ChangeSystemStateRequest::set_system_state(::surrogate::grpc::SystemState value) {
  _internal_set_system_state(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.ChangeSystemStateRequest.system_state)
}
inline ::surrogate::grpc::SystemState ChangeSystemStateRequest::_internal_system_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::SystemState>(_impl_.system_state_);
}
inline void ChangeSystemStateRequest::_internal_set_system_state(::surrogate::grpc::SystemState value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.system_state_ = value;
}

// -------------------------------------------------------------------

// SystemStateReply

// .surrogate.grpc.CommandId command_id = 1;
inline void SystemStateReply::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId SystemStateReply::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.SystemStateReply.command_id)
  return _internal_command_id();
}
inline void SystemStateReply::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.SystemStateReply.command_id)
}
inline ::surrogate::grpc::CommandId SystemStateReply::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void SystemStateReply::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// .surrogate.grpc.SystemState system_state = 2;
inline void SystemStateReply::clear_system_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.system_state_ = 0;
}
inline ::surrogate::grpc::SystemState SystemStateReply::system_state() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.SystemStateReply.system_state)
  return _internal_system_state();
}
inline void SystemStateReply::set_system_state(::surrogate::grpc::SystemState value) {
  _internal_set_system_state(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.SystemStateReply.system_state)
}
inline ::surrogate::grpc::SystemState SystemStateReply::_internal_system_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::SystemState>(_impl_.system_state_);
}
inline void SystemStateReply::_internal_set_system_state(::surrogate::grpc::SystemState value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.system_state_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msgs_5fsystem_2eproto_2epb_2eh
