// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_common.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msgs_5fcommon_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msgs_5fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msgs_5fcommon_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msgs_5fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msgs_5fcommon_2eproto;
namespace surrogate {
namespace grpc {
class DefaultReply;
struct DefaultReplyDefaultTypeInternal;
extern DefaultReplyDefaultTypeInternal _DefaultReply_default_instance_;
class EmptyReply;
struct EmptyReplyDefaultTypeInternal;
extern EmptyReplyDefaultTypeInternal _EmptyReply_default_instance_;
class EmptyRequest;
struct EmptyRequestDefaultTypeInternal;
extern EmptyRequestDefaultTypeInternal _EmptyRequest_default_instance_;
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace surrogate {
namespace grpc {
enum CommandId : int {
  CMD_NULL = 0,
  CMD_SYETEM_RESET = 1,
  CMD_SYSTEM_EMERGENCY_STOP = 2,
  CMD_SET_DESIRED_STATE = 100,
  CommandId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  CommandId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool CommandId_IsValid(int value);
extern const uint32_t CommandId_internal_data_[];
constexpr CommandId CommandId_MIN = static_cast<CommandId>(0);
constexpr CommandId CommandId_MAX = static_cast<CommandId>(100);
constexpr int CommandId_ARRAYSIZE = 100 + 1;
const ::google::protobuf::EnumDescriptor*
CommandId_descriptor();
template <typename T>
const std::string& CommandId_Name(T value) {
  static_assert(std::is_same<T, CommandId>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to CommandId_Name().");
  return ::google::protobuf::internal::NameOfEnum(CommandId_descriptor(), value);
}
inline bool CommandId_Parse(absl::string_view name, CommandId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CommandId>(
      CommandId_descriptor(), name, value);
}
enum SystemState : int {
  SS_OFF = 0,
  SS_ON = 1,
  SS_RECOVERY = 2,
  SS_EMERGENCY_STOP = 3,
  SystemState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SystemState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SystemState_IsValid(int value);
extern const uint32_t SystemState_internal_data_[];
constexpr SystemState SystemState_MIN = static_cast<SystemState>(0);
constexpr SystemState SystemState_MAX = static_cast<SystemState>(3);
constexpr int SystemState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
SystemState_descriptor();
template <typename T>
const std::string& SystemState_Name(T value) {
  static_assert(std::is_same<T, SystemState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SystemState_Name().");
  return SystemState_Name(static_cast<SystemState>(value));
}
template <>
inline const std::string& SystemState_Name(SystemState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SystemState_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool SystemState_Parse(absl::string_view name, SystemState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemState>(
      SystemState_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class EmptyRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:surrogate.grpc.EmptyRequest) */ {
 public:
  inline EmptyRequest() : EmptyRequest(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmptyRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmptyRequest(const EmptyRequest& from) : EmptyRequest(nullptr, from) {}
  inline EmptyRequest(EmptyRequest&& from) noexcept
      : EmptyRequest(nullptr, std::move(from)) {}
  inline EmptyRequest& operator=(const EmptyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmptyRequest& operator=(EmptyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmptyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmptyRequest* internal_default_instance() {
    return reinterpret_cast<const EmptyRequest*>(
        &_EmptyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EmptyRequest& a, EmptyRequest& b) { a.Swap(&b); }
  inline void Swap(EmptyRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmptyRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmptyRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<EmptyRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const EmptyRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const EmptyRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.EmptyRequest"; }

 protected:
  explicit EmptyRequest(::google::protobuf::Arena* arena);
  EmptyRequest(::google::protobuf::Arena* arena, const EmptyRequest& from);
  EmptyRequest(::google::protobuf::Arena* arena, EmptyRequest&& from) noexcept
      : EmptyRequest(arena) {
    *this = ::std::move(from);
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:surrogate.grpc.EmptyRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_msgs_5fcommon_2eproto;
};
// -------------------------------------------------------------------

class EmptyReply final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:surrogate.grpc.EmptyReply) */ {
 public:
  inline EmptyReply() : EmptyReply(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmptyReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmptyReply(const EmptyReply& from) : EmptyReply(nullptr, from) {}
  inline EmptyReply(EmptyReply&& from) noexcept
      : EmptyReply(nullptr, std::move(from)) {}
  inline EmptyReply& operator=(const EmptyReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmptyReply& operator=(EmptyReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmptyReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmptyReply* internal_default_instance() {
    return reinterpret_cast<const EmptyReply*>(
        &_EmptyReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EmptyReply& a, EmptyReply& b) { a.Swap(&b); }
  inline void Swap(EmptyReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmptyReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmptyReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<EmptyReply>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const EmptyReply& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const EmptyReply& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.EmptyReply"; }

 protected:
  explicit EmptyReply(::google::protobuf::Arena* arena);
  EmptyReply(::google::protobuf::Arena* arena, const EmptyReply& from);
  EmptyReply(::google::protobuf::Arena* arena, EmptyReply&& from) noexcept
      : EmptyReply(arena) {
    *this = ::std::move(from);
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:surrogate.grpc.EmptyReply)
 private:
  class _Internal;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_msgs_5fcommon_2eproto;
};
// -------------------------------------------------------------------

class DefaultReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.DefaultReply) */ {
 public:
  inline DefaultReply() : DefaultReply(nullptr) {}
  ~DefaultReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DefaultReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline DefaultReply(const DefaultReply& from) : DefaultReply(nullptr, from) {}
  inline DefaultReply(DefaultReply&& from) noexcept
      : DefaultReply(nullptr, std::move(from)) {}
  inline DefaultReply& operator=(const DefaultReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline DefaultReply& operator=(DefaultReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DefaultReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const DefaultReply* internal_default_instance() {
    return reinterpret_cast<const DefaultReply*>(
        &_DefaultReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DefaultReply& a, DefaultReply& b) { a.Swap(&b); }
  inline void Swap(DefaultReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DefaultReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DefaultReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<DefaultReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DefaultReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DefaultReply& from) { DefaultReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DefaultReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.DefaultReply"; }

 protected:
  explicit DefaultReply(::google::protobuf::Arena* arena);
  DefaultReply(::google::protobuf::Arena* arena, const DefaultReply& from);
  DefaultReply(::google::protobuf::Arena* arena, DefaultReply&& from) noexcept
      : DefaultReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandIdFieldNumber = 1,
  };
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.DefaultReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    int command_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fcommon_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EmptyRequest

// -------------------------------------------------------------------

// EmptyReply

// -------------------------------------------------------------------

// DefaultReply

// .surrogate.grpc.CommandId command_id = 1;
inline void DefaultReply::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId DefaultReply::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.DefaultReply.command_id)
  return _internal_command_id();
}
inline void DefaultReply::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.DefaultReply.command_id)
}
inline ::surrogate::grpc::CommandId DefaultReply::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void DefaultReply::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::surrogate::grpc::CommandId> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::surrogate::grpc::CommandId>() {
  return ::surrogate::grpc::CommandId_descriptor();
}
template <>
struct is_proto_enum<::surrogate::grpc::SystemState> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::surrogate::grpc::SystemState>() {
  return ::surrogate::grpc::SystemState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msgs_5fcommon_2eproto_2epb_2eh
