// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_config.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msgs_5fconfig_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msgs_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "msgs_common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msgs_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msgs_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msgs_5fconfig_2eproto;
namespace surrogate {
namespace grpc {
class FTsensorFrame;
struct FTsensorFrameDefaultTypeInternal;
extern FTsensorFrameDefaultTypeInternal _FTsensorFrame_default_instance_;
class Frame;
struct FrameDefaultTypeInternal;
extern FrameDefaultTypeInternal _Frame_default_instance_;
class JointPos;
struct JointPosDefaultTypeInternal;
extern JointPosDefaultTypeInternal _JointPos_default_instance_;
class TaskPos;
struct TaskPosDefaultTypeInternal;
extern TaskPosDefaultTypeInternal _TaskPos_default_instance_;
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace surrogate {
namespace grpc {

// ===================================================================


// -------------------------------------------------------------------

class TaskPos final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.TaskPos) */ {
 public:
  inline TaskPos() : TaskPos(nullptr) {}
  ~TaskPos() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskPos(
      ::google::protobuf::internal::ConstantInitialized);

  inline TaskPos(const TaskPos& from) : TaskPos(nullptr, from) {}
  inline TaskPos(TaskPos&& from) noexcept
      : TaskPos(nullptr, std::move(from)) {}
  inline TaskPos& operator=(const TaskPos& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskPos& operator=(TaskPos&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskPos& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskPos* internal_default_instance() {
    return reinterpret_cast<const TaskPos*>(
        &_TaskPos_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TaskPos& a, TaskPos& b) { a.Swap(&b); }
  inline void Swap(TaskPos* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskPos* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskPos* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<TaskPos>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TaskPos& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TaskPos& from) { TaskPos::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskPos* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.TaskPos"; }

 protected:
  explicit TaskPos(::google::protobuf::Arena* arena);
  TaskPos(::google::protobuf::Arena* arena, const TaskPos& from);
  TaskPos(::google::protobuf::Arena* arena, TaskPos&& from) noexcept
      : TaskPos(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTposFieldNumber = 1,
  };
  // repeated float tpos = 1;
  int tpos_size() const;
  private:
  int _internal_tpos_size() const;

  public:
  void clear_tpos() ;
  float tpos(int index) const;
  void set_tpos(int index, float value);
  void add_tpos(float value);
  const ::google::protobuf::RepeatedField<float>& tpos() const;
  ::google::protobuf::RepeatedField<float>* mutable_tpos();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_tpos() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_tpos();

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.TaskPos)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> tpos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class JointPos final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.JointPos) */ {
 public:
  inline JointPos() : JointPos(nullptr) {}
  ~JointPos() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointPos(
      ::google::protobuf::internal::ConstantInitialized);

  inline JointPos(const JointPos& from) : JointPos(nullptr, from) {}
  inline JointPos(JointPos&& from) noexcept
      : JointPos(nullptr, std::move(from)) {}
  inline JointPos& operator=(const JointPos& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointPos& operator=(JointPos&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointPos& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointPos* internal_default_instance() {
    return reinterpret_cast<const JointPos*>(
        &_JointPos_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(JointPos& a, JointPos& b) { a.Swap(&b); }
  inline void Swap(JointPos* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointPos* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointPos* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<JointPos>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JointPos& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JointPos& from) { JointPos::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(JointPos* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.JointPos"; }

 protected:
  explicit JointPos(::google::protobuf::Arena* arena);
  JointPos(::google::protobuf::Arena* arena, const JointPos& from);
  JointPos(::google::protobuf::Arena* arena, JointPos&& from) noexcept
      : JointPos(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJposFieldNumber = 1,
  };
  // repeated float jpos = 1;
  int jpos_size() const;
  private:
  int _internal_jpos_size() const;

  public:
  void clear_jpos() ;
  float jpos(int index) const;
  void set_jpos(int index, float value);
  void add_jpos(float value);
  const ::google::protobuf::RepeatedField<float>& jpos() const;
  ::google::protobuf::RepeatedField<float>* mutable_jpos();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_jpos() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_jpos();

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.JointPos)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> jpos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class Frame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.Frame) */ {
 public:
  inline Frame() : Frame(nullptr) {}
  ~Frame() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Frame(
      ::google::protobuf::internal::ConstantInitialized);

  inline Frame(const Frame& from) : Frame(nullptr, from) {}
  inline Frame(Frame&& from) noexcept
      : Frame(nullptr, std::move(from)) {}
  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }
  inline Frame& operator=(Frame&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Frame& default_instance() {
    return *internal_default_instance();
  }
  static inline const Frame* internal_default_instance() {
    return reinterpret_cast<const Frame*>(
        &_Frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Frame& a, Frame& b) { a.Swap(&b); }
  inline void Swap(Frame* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Frame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Frame* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Frame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Frame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Frame& from) { Frame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Frame* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.Frame"; }

 protected:
  explicit Frame(::google::protobuf::Arena* arena);
  Frame(::google::protobuf::Arena* arena, const Frame& from);
  Frame(::google::protobuf::Arena* arena, Frame&& from) noexcept
      : Frame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFposFieldNumber = 1,
  };
  // repeated float fpos = 1;
  int fpos_size() const;
  private:
  int _internal_fpos_size() const;

  public:
  void clear_fpos() ;
  float fpos(int index) const;
  void set_fpos(int index, float value);
  void add_fpos(float value);
  const ::google::protobuf::RepeatedField<float>& fpos() const;
  ::google::protobuf::RepeatedField<float>* mutable_fpos();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_fpos() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_fpos();

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.Frame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> fpos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class FTsensorFrame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.FTsensorFrame) */ {
 public:
  inline FTsensorFrame() : FTsensorFrame(nullptr) {}
  ~FTsensorFrame() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FTsensorFrame(
      ::google::protobuf::internal::ConstantInitialized);

  inline FTsensorFrame(const FTsensorFrame& from) : FTsensorFrame(nullptr, from) {}
  inline FTsensorFrame(FTsensorFrame&& from) noexcept
      : FTsensorFrame(nullptr, std::move(from)) {}
  inline FTsensorFrame& operator=(const FTsensorFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline FTsensorFrame& operator=(FTsensorFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FTsensorFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const FTsensorFrame* internal_default_instance() {
    return reinterpret_cast<const FTsensorFrame*>(
        &_FTsensorFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FTsensorFrame& a, FTsensorFrame& b) { a.Swap(&b); }
  inline void Swap(FTsensorFrame* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FTsensorFrame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FTsensorFrame* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<FTsensorFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FTsensorFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FTsensorFrame& from) { FTsensorFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(FTsensorFrame* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.FTsensorFrame"; }

 protected:
  explicit FTsensorFrame(::google::protobuf::Arena* arena);
  FTsensorFrame(::google::protobuf::Arena* arena, const FTsensorFrame& from);
  FTsensorFrame(::google::protobuf::Arena* arena, FTsensorFrame&& from) noexcept
      : FTsensorFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // float translation = 1;
  void clear_translation() ;
  float translation() const;
  void set_translation(float value);

  private:
  float _internal_translation() const;
  void _internal_set_translation(float value);

  public:
  // float rotation = 2;
  void clear_rotation() ;
  float rotation() const;
  void set_rotation(float value);

  private:
  float _internal_rotation() const;
  void _internal_set_rotation(float value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.FTsensorFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    float translation_;
    float rotation_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fconfig_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Frame

// repeated float fpos = 1;
inline int Frame::_internal_fpos_size() const {
  return _internal_fpos().size();
}
inline int Frame::fpos_size() const {
  return _internal_fpos_size();
}
inline void Frame::clear_fpos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.fpos_.Clear();
}
inline float Frame::fpos(int index) const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.Frame.fpos)
  return _internal_fpos().Get(index);
}
inline void Frame::set_fpos(int index, float value) {
  _internal_mutable_fpos()->Set(index, value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.Frame.fpos)
}
inline void Frame::add_fpos(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_fpos()->Add(value);
  // @@protoc_insertion_point(field_add:surrogate.grpc.Frame.fpos)
}
inline const ::google::protobuf::RepeatedField<float>& Frame::fpos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:surrogate.grpc.Frame.fpos)
  return _internal_fpos();
}
inline ::google::protobuf::RepeatedField<float>* Frame::mutable_fpos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:surrogate.grpc.Frame.fpos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_fpos();
}
inline const ::google::protobuf::RepeatedField<float>&
Frame::_internal_fpos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.fpos_;
}
inline ::google::protobuf::RepeatedField<float>* Frame::_internal_mutable_fpos() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.fpos_;
}

// -------------------------------------------------------------------

// FTsensorFrame

// float translation = 1;
inline void FTsensorFrame::clear_translation() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.translation_ = 0;
}
inline float FTsensorFrame::translation() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.FTsensorFrame.translation)
  return _internal_translation();
}
inline void FTsensorFrame::set_translation(float value) {
  _internal_set_translation(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.FTsensorFrame.translation)
}
inline float FTsensorFrame::_internal_translation() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.translation_;
}
inline void FTsensorFrame::_internal_set_translation(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.translation_ = value;
}

// float rotation = 2;
inline void FTsensorFrame::clear_rotation() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rotation_ = 0;
}
inline float FTsensorFrame::rotation() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.FTsensorFrame.rotation)
  return _internal_rotation();
}
inline void FTsensorFrame::set_rotation(float value) {
  _internal_set_rotation(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.FTsensorFrame.rotation)
}
inline float FTsensorFrame::_internal_rotation() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rotation_;
}
inline void FTsensorFrame::_internal_set_rotation(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rotation_ = value;
}

// -------------------------------------------------------------------

// JointPos

// repeated float jpos = 1;
inline int JointPos::_internal_jpos_size() const {
  return _internal_jpos().size();
}
inline int JointPos::jpos_size() const {
  return _internal_jpos_size();
}
inline void JointPos::clear_jpos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.jpos_.Clear();
}
inline float JointPos::jpos(int index) const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.JointPos.jpos)
  return _internal_jpos().Get(index);
}
inline void JointPos::set_jpos(int index, float value) {
  _internal_mutable_jpos()->Set(index, value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.JointPos.jpos)
}
inline void JointPos::add_jpos(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_jpos()->Add(value);
  // @@protoc_insertion_point(field_add:surrogate.grpc.JointPos.jpos)
}
inline const ::google::protobuf::RepeatedField<float>& JointPos::jpos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:surrogate.grpc.JointPos.jpos)
  return _internal_jpos();
}
inline ::google::protobuf::RepeatedField<float>* JointPos::mutable_jpos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:surrogate.grpc.JointPos.jpos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_jpos();
}
inline const ::google::protobuf::RepeatedField<float>&
JointPos::_internal_jpos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.jpos_;
}
inline ::google::protobuf::RepeatedField<float>* JointPos::_internal_mutable_jpos() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.jpos_;
}

// -------------------------------------------------------------------

// TaskPos

// repeated float tpos = 1;
inline int TaskPos::_internal_tpos_size() const {
  return _internal_tpos().size();
}
inline int TaskPos::tpos_size() const {
  return _internal_tpos_size();
}
inline void TaskPos::clear_tpos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tpos_.Clear();
}
inline float TaskPos::tpos(int index) const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.TaskPos.tpos)
  return _internal_tpos().Get(index);
}
inline void TaskPos::set_tpos(int index, float value) {
  _internal_mutable_tpos()->Set(index, value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.TaskPos.tpos)
}
inline void TaskPos::add_tpos(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_tpos()->Add(value);
  // @@protoc_insertion_point(field_add:surrogate.grpc.TaskPos.tpos)
}
inline const ::google::protobuf::RepeatedField<float>& TaskPos::tpos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:surrogate.grpc.TaskPos.tpos)
  return _internal_tpos();
}
inline ::google::protobuf::RepeatedField<float>* TaskPos::mutable_tpos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:surrogate.grpc.TaskPos.tpos)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_tpos();
}
inline const ::google::protobuf::RepeatedField<float>&
TaskPos::_internal_tpos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tpos_;
}
inline ::google::protobuf::RepeatedField<float>* TaskPos::_internal_mutable_tpos() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.tpos_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msgs_5fconfig_2eproto_2epb_2eh
