// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_control.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msgs_5fcontrol_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msgs_5fcontrol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "msgs_common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msgs_5fcontrol_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msgs_5fcontrol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msgs_5fcontrol_2eproto;
namespace surrogate {
namespace grpc {
class ControlDefaultReply;
struct ControlDefaultReplyDefaultTypeInternal;
extern ControlDefaultReplyDefaultTypeInternal _ControlDefaultReply_default_instance_;
class MoveJRequest;
struct MoveJRequestDefaultTypeInternal;
extern MoveJRequestDefaultTypeInternal _MoveJRequest_default_instance_;
class MoveTRequest;
struct MoveTRequestDefaultTypeInternal;
extern MoveTRequestDefaultTypeInternal _MoveTRequest_default_instance_;
class SetMobileStateRequest;
struct SetMobileStateRequestDefaultTypeInternal;
extern SetMobileStateRequestDefaultTypeInternal _SetMobileStateRequest_default_instance_;
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace surrogate {
namespace grpc {

// ===================================================================


// -------------------------------------------------------------------

class SetMobileStateRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.SetMobileStateRequest) */ {
 public:
  inline SetMobileStateRequest() : SetMobileStateRequest(nullptr) {}
  ~SetMobileStateRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetMobileStateRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline SetMobileStateRequest(const SetMobileStateRequest& from) : SetMobileStateRequest(nullptr, from) {}
  inline SetMobileStateRequest(SetMobileStateRequest&& from) noexcept
      : SetMobileStateRequest(nullptr, std::move(from)) {}
  inline SetMobileStateRequest& operator=(const SetMobileStateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetMobileStateRequest& operator=(SetMobileStateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetMobileStateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetMobileStateRequest* internal_default_instance() {
    return reinterpret_cast<const SetMobileStateRequest*>(
        &_SetMobileStateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SetMobileStateRequest& a, SetMobileStateRequest& b) { a.Swap(&b); }
  inline void Swap(SetMobileStateRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetMobileStateRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetMobileStateRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<SetMobileStateRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetMobileStateRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetMobileStateRequest& from) { SetMobileStateRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SetMobileStateRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.SetMobileStateRequest"; }

 protected:
  explicit SetMobileStateRequest(::google::protobuf::Arena* arena);
  SetMobileStateRequest(::google::protobuf::Arena* arena, const SetMobileStateRequest& from);
  SetMobileStateRequest(::google::protobuf::Arena* arena, SetMobileStateRequest&& from) noexcept
      : SetMobileStateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandIdFieldNumber = 1,
    kWheelVelFieldNumber = 2,
    kSteeringPosFieldNumber = 3,
  };
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // float wheel_vel = 2;
  void clear_wheel_vel() ;
  float wheel_vel() const;
  void set_wheel_vel(float value);

  private:
  float _internal_wheel_vel() const;
  void _internal_set_wheel_vel(float value);

  public:
  // float steering_pos = 3;
  void clear_steering_pos() ;
  float steering_pos() const;
  void set_steering_pos(float value);

  private:
  float _internal_steering_pos() const;
  void _internal_set_steering_pos(float value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.SetMobileStateRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    int command_id_;
    float wheel_vel_;
    float steering_pos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class MoveTRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.MoveTRequest) */ {
 public:
  inline MoveTRequest() : MoveTRequest(nullptr) {}
  ~MoveTRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MoveTRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline MoveTRequest(const MoveTRequest& from) : MoveTRequest(nullptr, from) {}
  inline MoveTRequest(MoveTRequest&& from) noexcept
      : MoveTRequest(nullptr, std::move(from)) {}
  inline MoveTRequest& operator=(const MoveTRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoveTRequest& operator=(MoveTRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MoveTRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MoveTRequest* internal_default_instance() {
    return reinterpret_cast<const MoveTRequest*>(
        &_MoveTRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MoveTRequest& a, MoveTRequest& b) { a.Swap(&b); }
  inline void Swap(MoveTRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoveTRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MoveTRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<MoveTRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MoveTRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MoveTRequest& from) { MoveTRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MoveTRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.MoveTRequest"; }

 protected:
  explicit MoveTRequest(::google::protobuf::Arena* arena);
  MoveTRequest(::google::protobuf::Arena* arena, const MoveTRequest& from);
  MoveTRequest(::google::protobuf::Arena* arena, MoveTRequest&& from) noexcept
      : MoveTRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPDesFieldNumber = 2,
    kCommandIdFieldNumber = 1,
  };
  // repeated float p_des = 2;
  int p_des_size() const;
  private:
  int _internal_p_des_size() const;

  public:
  void clear_p_des() ;
  float p_des(int index) const;
  void set_p_des(int index, float value);
  void add_p_des(float value);
  const ::google::protobuf::RepeatedField<float>& p_des() const;
  ::google::protobuf::RepeatedField<float>* mutable_p_des();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_p_des() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_p_des();

  public:
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.MoveTRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> p_des_;
    int command_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class MoveJRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.MoveJRequest) */ {
 public:
  inline MoveJRequest() : MoveJRequest(nullptr) {}
  ~MoveJRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MoveJRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline MoveJRequest(const MoveJRequest& from) : MoveJRequest(nullptr, from) {}
  inline MoveJRequest(MoveJRequest&& from) noexcept
      : MoveJRequest(nullptr, std::move(from)) {}
  inline MoveJRequest& operator=(const MoveJRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoveJRequest& operator=(MoveJRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MoveJRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MoveJRequest* internal_default_instance() {
    return reinterpret_cast<const MoveJRequest*>(
        &_MoveJRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MoveJRequest& a, MoveJRequest& b) { a.Swap(&b); }
  inline void Swap(MoveJRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoveJRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MoveJRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<MoveJRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MoveJRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MoveJRequest& from) { MoveJRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MoveJRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.MoveJRequest"; }

 protected:
  explicit MoveJRequest(::google::protobuf::Arena* arena);
  MoveJRequest(::google::protobuf::Arena* arena, const MoveJRequest& from);
  MoveJRequest(::google::protobuf::Arena* arena, MoveJRequest&& from) noexcept
      : MoveJRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQDesFieldNumber = 2,
    kCommandIdFieldNumber = 1,
  };
  // repeated float q_des = 2;
  int q_des_size() const;
  private:
  int _internal_q_des_size() const;

  public:
  void clear_q_des() ;
  float q_des(int index) const;
  void set_q_des(int index, float value);
  void add_q_des(float value);
  const ::google::protobuf::RepeatedField<float>& q_des() const;
  ::google::protobuf::RepeatedField<float>* mutable_q_des();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_q_des() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_q_des();

  public:
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.MoveJRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> q_des_;
    int command_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class ControlDefaultReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:surrogate.grpc.ControlDefaultReply) */ {
 public:
  inline ControlDefaultReply() : ControlDefaultReply(nullptr) {}
  ~ControlDefaultReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ControlDefaultReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline ControlDefaultReply(const ControlDefaultReply& from) : ControlDefaultReply(nullptr, from) {}
  inline ControlDefaultReply(ControlDefaultReply&& from) noexcept
      : ControlDefaultReply(nullptr, std::move(from)) {}
  inline ControlDefaultReply& operator=(const ControlDefaultReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlDefaultReply& operator=(ControlDefaultReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlDefaultReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlDefaultReply* internal_default_instance() {
    return reinterpret_cast<const ControlDefaultReply*>(
        &_ControlDefaultReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ControlDefaultReply& a, ControlDefaultReply& b) { a.Swap(&b); }
  inline void Swap(ControlDefaultReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlDefaultReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlDefaultReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ControlDefaultReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlDefaultReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ControlDefaultReply& from) { ControlDefaultReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlDefaultReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "surrogate.grpc.ControlDefaultReply"; }

 protected:
  explicit ControlDefaultReply(::google::protobuf::Arena* arena);
  ControlDefaultReply(::google::protobuf::Arena* arena, const ControlDefaultReply& from);
  ControlDefaultReply(::google::protobuf::Arena* arena, ControlDefaultReply&& from) noexcept
      : ControlDefaultReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kCommandIdFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // .surrogate.grpc.CommandId command_id = 1;
  void clear_command_id() ;
  ::surrogate::grpc::CommandId command_id() const;
  void set_command_id(::surrogate::grpc::CommandId value);

  private:
  ::surrogate::grpc::CommandId _internal_command_id() const;
  void _internal_set_command_id(::surrogate::grpc::CommandId value);

  public:
  // @@protoc_insertion_point(class_scope:surrogate.grpc.ControlDefaultReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      50, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr message_;
    int command_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msgs_5fcontrol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MoveJRequest

// .surrogate.grpc.CommandId command_id = 1;
inline void MoveJRequest::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId MoveJRequest::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.MoveJRequest.command_id)
  return _internal_command_id();
}
inline void MoveJRequest::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.MoveJRequest.command_id)
}
inline ::surrogate::grpc::CommandId MoveJRequest::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void MoveJRequest::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// repeated float q_des = 2;
inline int MoveJRequest::_internal_q_des_size() const {
  return _internal_q_des().size();
}
inline int MoveJRequest::q_des_size() const {
  return _internal_q_des_size();
}
inline void MoveJRequest::clear_q_des() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.q_des_.Clear();
}
inline float MoveJRequest::q_des(int index) const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.MoveJRequest.q_des)
  return _internal_q_des().Get(index);
}
inline void MoveJRequest::set_q_des(int index, float value) {
  _internal_mutable_q_des()->Set(index, value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.MoveJRequest.q_des)
}
inline void MoveJRequest::add_q_des(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_q_des()->Add(value);
  // @@protoc_insertion_point(field_add:surrogate.grpc.MoveJRequest.q_des)
}
inline const ::google::protobuf::RepeatedField<float>& MoveJRequest::q_des() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:surrogate.grpc.MoveJRequest.q_des)
  return _internal_q_des();
}
inline ::google::protobuf::RepeatedField<float>* MoveJRequest::mutable_q_des()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:surrogate.grpc.MoveJRequest.q_des)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_q_des();
}
inline const ::google::protobuf::RepeatedField<float>&
MoveJRequest::_internal_q_des() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.q_des_;
}
inline ::google::protobuf::RepeatedField<float>* MoveJRequest::_internal_mutable_q_des() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.q_des_;
}

// -------------------------------------------------------------------

// MoveTRequest

// .surrogate.grpc.CommandId command_id = 1;
inline void MoveTRequest::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId MoveTRequest::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.MoveTRequest.command_id)
  return _internal_command_id();
}
inline void MoveTRequest::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.MoveTRequest.command_id)
}
inline ::surrogate::grpc::CommandId MoveTRequest::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void MoveTRequest::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// repeated float p_des = 2;
inline int MoveTRequest::_internal_p_des_size() const {
  return _internal_p_des().size();
}
inline int MoveTRequest::p_des_size() const {
  return _internal_p_des_size();
}
inline void MoveTRequest::clear_p_des() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.p_des_.Clear();
}
inline float MoveTRequest::p_des(int index) const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.MoveTRequest.p_des)
  return _internal_p_des().Get(index);
}
inline void MoveTRequest::set_p_des(int index, float value) {
  _internal_mutable_p_des()->Set(index, value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.MoveTRequest.p_des)
}
inline void MoveTRequest::add_p_des(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_p_des()->Add(value);
  // @@protoc_insertion_point(field_add:surrogate.grpc.MoveTRequest.p_des)
}
inline const ::google::protobuf::RepeatedField<float>& MoveTRequest::p_des() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:surrogate.grpc.MoveTRequest.p_des)
  return _internal_p_des();
}
inline ::google::protobuf::RepeatedField<float>* MoveTRequest::mutable_p_des()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:surrogate.grpc.MoveTRequest.p_des)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_p_des();
}
inline const ::google::protobuf::RepeatedField<float>&
MoveTRequest::_internal_p_des() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.p_des_;
}
inline ::google::protobuf::RepeatedField<float>* MoveTRequest::_internal_mutable_p_des() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.p_des_;
}

// -------------------------------------------------------------------

// SetMobileStateRequest

// .surrogate.grpc.CommandId command_id = 1;
inline void SetMobileStateRequest::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId SetMobileStateRequest::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.SetMobileStateRequest.command_id)
  return _internal_command_id();
}
inline void SetMobileStateRequest::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.SetMobileStateRequest.command_id)
}
inline ::surrogate::grpc::CommandId SetMobileStateRequest::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void SetMobileStateRequest::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// float wheel_vel = 2;
inline void SetMobileStateRequest::clear_wheel_vel() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.wheel_vel_ = 0;
}
inline float SetMobileStateRequest::wheel_vel() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.SetMobileStateRequest.wheel_vel)
  return _internal_wheel_vel();
}
inline void SetMobileStateRequest::set_wheel_vel(float value) {
  _internal_set_wheel_vel(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.SetMobileStateRequest.wheel_vel)
}
inline float SetMobileStateRequest::_internal_wheel_vel() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.wheel_vel_;
}
inline void SetMobileStateRequest::_internal_set_wheel_vel(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.wheel_vel_ = value;
}

// float steering_pos = 3;
inline void SetMobileStateRequest::clear_steering_pos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.steering_pos_ = 0;
}
inline float SetMobileStateRequest::steering_pos() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.SetMobileStateRequest.steering_pos)
  return _internal_steering_pos();
}
inline void SetMobileStateRequest::set_steering_pos(float value) {
  _internal_set_steering_pos(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.SetMobileStateRequest.steering_pos)
}
inline float SetMobileStateRequest::_internal_steering_pos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.steering_pos_;
}
inline void SetMobileStateRequest::_internal_set_steering_pos(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.steering_pos_ = value;
}

// -------------------------------------------------------------------

// ControlDefaultReply

// .surrogate.grpc.CommandId command_id = 1;
inline void ControlDefaultReply::clear_command_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = 0;
}
inline ::surrogate::grpc::CommandId ControlDefaultReply::command_id() const {
  // @@protoc_insertion_point(field_get:surrogate.grpc.ControlDefaultReply.command_id)
  return _internal_command_id();
}
inline void ControlDefaultReply::set_command_id(::surrogate::grpc::CommandId value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:surrogate.grpc.ControlDefaultReply.command_id)
}
inline ::surrogate::grpc::CommandId ControlDefaultReply::_internal_command_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::surrogate::grpc::CommandId>(_impl_.command_id_);
}
inline void ControlDefaultReply::_internal_set_command_id(::surrogate::grpc::CommandId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.command_id_ = value;
}

// string message = 2;
inline void ControlDefaultReply::clear_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ControlDefaultReply::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:surrogate.grpc.ControlDefaultReply.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlDefaultReply::set_message(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:surrogate.grpc.ControlDefaultReply.message)
}
inline std::string* ControlDefaultReply::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:surrogate.grpc.ControlDefaultReply.message)
  return _s;
}
inline const std::string& ControlDefaultReply::_internal_message() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.message_.Get();
}
inline void ControlDefaultReply::_internal_set_message(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* ControlDefaultReply::_internal_mutable_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* ControlDefaultReply::release_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:surrogate.grpc.ControlDefaultReply.message)
  return _impl_.message_.Release();
}
inline void ControlDefaultReply::set_allocated_message(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.message_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:surrogate.grpc.ControlDefaultReply.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msgs_5fcontrol_2eproto_2epb_2eh
