// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_common.proto
// Protobuf C++ Version: 5.26.1

#include "msgs_common.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace surrogate {
namespace grpc {
      template <typename>
PROTOBUF_CONSTEXPR EmptyRequest::EmptyRequest(::_pbi::ConstantInitialized) {}
struct EmptyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyRequestDefaultTypeInternal() {}
  union {
    EmptyRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyRequestDefaultTypeInternal _EmptyRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR EmptyReply::EmptyReply(::_pbi::ConstantInitialized) {}
struct EmptyReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyReplyDefaultTypeInternal() {}
  union {
    EmptyReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyReplyDefaultTypeInternal _EmptyReply_default_instance_;

inline constexpr DefaultReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DefaultReply::DefaultReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DefaultReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DefaultReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DefaultReplyDefaultTypeInternal() {}
  union {
    DefaultReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DefaultReplyDefaultTypeInternal _DefaultReply_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fcommon_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msgs_5fcommon_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msgs_5fcommon_2eproto = nullptr;
const ::uint32_t
    TableStruct_msgs_5fcommon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::EmptyRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::EmptyReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::DefaultReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::DefaultReply, _impl_.command_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::surrogate::grpc::EmptyRequest)},
        {8, -1, -1, sizeof(::surrogate::grpc::EmptyReply)},
        {16, -1, -1, sizeof(::surrogate::grpc::DefaultReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::surrogate::grpc::_EmptyRequest_default_instance_._instance,
    &::surrogate::grpc::_EmptyReply_default_instance_._instance,
    &::surrogate::grpc::_DefaultReply_default_instance_._instance,
};
const char descriptor_table_protodef_msgs_5fcommon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021msgs_common.proto\022\016surrogate.grpc\"\016\n\014E"
    "mptyRequest\"\014\n\nEmptyReply\"=\n\014DefaultRepl"
    "y\022-\n\ncommand_id\030\001 \001(\0162\031.surrogate.grpc.C"
    "ommandId*i\n\tCommandId\022\014\n\010CMD_NULL\020\000\022\024\n\020C"
    "MD_SYETEM_RESET\020\001\022\035\n\031CMD_SYSTEM_EMERGENC"
    "Y_STOP\020\002\022\031\n\025CMD_SET_DESIRED_STATE\020d*L\n\013S"
    "ystemState\022\n\n\006SS_OFF\020\000\022\t\n\005SS_ON\020\001\022\017\n\013SS_"
    "RECOVERY\020\002\022\025\n\021SS_EMERGENCY_STOP\020\003b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_msgs_5fcommon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fcommon_2eproto = {
    false,
    false,
    321,
    descriptor_table_protodef_msgs_5fcommon_2eproto,
    "msgs_common.proto",
    &descriptor_table_msgs_5fcommon_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_msgs_5fcommon_2eproto::offsets,
    file_level_metadata_msgs_5fcommon_2eproto,
    file_level_enum_descriptors_msgs_5fcommon_2eproto,
    file_level_service_descriptors_msgs_5fcommon_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fcommon_2eproto_getter() {
  return &descriptor_table_msgs_5fcommon_2eproto;
}
namespace surrogate {
namespace grpc {
const ::google::protobuf::EnumDescriptor* CommandId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto);
  return file_level_enum_descriptors_msgs_5fcommon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommandId_internal_data_[] = {
    196608u, 65536u, 100u, };
bool CommandId_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, CommandId_internal_data_);
}
const ::google::protobuf::EnumDescriptor* SystemState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto);
  return file_level_enum_descriptors_msgs_5fcommon_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t SystemState_internal_data_[] = {
    262144u, 0u, };
bool SystemState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class EmptyRequest::_Internal {
 public:
};

EmptyRequest::EmptyRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.EmptyRequest)
}
EmptyRequest::EmptyRequest(
    ::google::protobuf::Arena* arena,
    const EmptyRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  EmptyRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.EmptyRequest)
}









::google::protobuf::Metadata EmptyRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto_getter,
                                   &descriptor_table_msgs_5fcommon_2eproto_once,
                                   file_level_metadata_msgs_5fcommon_2eproto[0]);
}
// ===================================================================

class EmptyReply::_Internal {
 public:
};

EmptyReply::EmptyReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.EmptyReply)
}
EmptyReply::EmptyReply(
    ::google::protobuf::Arena* arena,
    const EmptyReply& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  EmptyReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.EmptyReply)
}









::google::protobuf::Metadata EmptyReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto_getter,
                                   &descriptor_table_msgs_5fcommon_2eproto_once,
                                   file_level_metadata_msgs_5fcommon_2eproto[1]);
}
// ===================================================================

class DefaultReply::_Internal {
 public:
};

DefaultReply::DefaultReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.DefaultReply)
}
DefaultReply::DefaultReply(
    ::google::protobuf::Arena* arena, const DefaultReply& from)
    : DefaultReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DefaultReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DefaultReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.command_id_ = {};
}
DefaultReply::~DefaultReply() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.DefaultReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DefaultReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DefaultReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(DefaultReply, _impl_._cached_size_),
              false,
          },
          &DefaultReply::MergeImpl,
          &DefaultReply::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void DefaultReply::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.DefaultReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DefaultReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DefaultReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DefaultReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::DefaultReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DefaultReply, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DefaultReply, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(DefaultReply, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DefaultReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.DefaultReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.DefaultReply)
  return target;
}

::size_t DefaultReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.DefaultReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DefaultReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DefaultReply*>(&to_msg);
  auto& from = static_cast<const DefaultReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.DefaultReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DefaultReply::CopyFrom(const DefaultReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.DefaultReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DefaultReply::IsInitialized() const {
  return true;
}

void DefaultReply::InternalSwap(DefaultReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.command_id_, other->_impl_.command_id_);
}

::google::protobuf::Metadata DefaultReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto_getter,
                                   &descriptor_table_msgs_5fcommon_2eproto_once,
                                   file_level_metadata_msgs_5fcommon_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_msgs_5fcommon_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
