// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_motion.proto
// Protobuf C++ Version: 5.26.1

#include "msgs_motion.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace surrogate {
namespace grpc {

inline constexpr MotionData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MotionData::MotionData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MotionDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MotionDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MotionDataDefaultTypeInternal() {}
  union {
    MotionData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MotionDataDefaultTypeInternal _MotionData_default_instance_;

inline constexpr MobileMotionData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : system_state_{static_cast< ::surrogate::grpc::SystemState >(0)},
        wheel_vel_{0},
        steering_pos_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MobileMotionData::MobileMotionData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MobileMotionDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MobileMotionDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MobileMotionDataDefaultTypeInternal() {}
  union {
    MobileMotionData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MobileMotionDataDefaultTypeInternal _MobileMotionData_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fmotion_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msgs_5fmotion_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msgs_5fmotion_2eproto = nullptr;
const ::uint32_t
    TableStruct_msgs_5fmotion_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MotionData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MotionData, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MobileMotionData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MobileMotionData, _impl_.system_state_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MobileMotionData, _impl_.wheel_vel_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::MobileMotionData, _impl_.steering_pos_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::surrogate::grpc::MotionData)},
        {9, -1, -1, sizeof(::surrogate::grpc::MobileMotionData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::surrogate::grpc::_MotionData_default_instance_._instance,
    &::surrogate::grpc::_MobileMotionData_default_instance_._instance,
};
const char descriptor_table_protodef_msgs_5fmotion_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021msgs_motion.proto\022\016surrogate.grpc\032\021msg"
    "s_common.proto\"\035\n\nMotionData\022\017\n\007message\030"
    "\001 \001(\t\"n\n\020MobileMotionData\0221\n\014system_stat"
    "e\030\001 \001(\0162\033.surrogate.grpc.SystemState\022\021\n\t"
    "wheel_vel\030\002 \001(\002\022\024\n\014steering_pos\030\003 \001(\002b\006p"
    "roto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msgs_5fmotion_2eproto_deps[1] =
    {
        &::descriptor_table_msgs_5fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_msgs_5fmotion_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fmotion_2eproto = {
    false,
    false,
    205,
    descriptor_table_protodef_msgs_5fmotion_2eproto,
    "msgs_motion.proto",
    &descriptor_table_msgs_5fmotion_2eproto_once,
    descriptor_table_msgs_5fmotion_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_msgs_5fmotion_2eproto::offsets,
    file_level_metadata_msgs_5fmotion_2eproto,
    file_level_enum_descriptors_msgs_5fmotion_2eproto,
    file_level_service_descriptors_msgs_5fmotion_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fmotion_2eproto_getter() {
  return &descriptor_table_msgs_5fmotion_2eproto;
}
namespace surrogate {
namespace grpc {
// ===================================================================

class MotionData::_Internal {
 public:
};

MotionData::MotionData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.MotionData)
}
inline PROTOBUF_NDEBUG_INLINE MotionData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

MotionData::MotionData(
    ::google::protobuf::Arena* arena,
    const MotionData& from)
    : ::google::protobuf::Message(arena) {
  MotionData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.MotionData)
}
inline PROTOBUF_NDEBUG_INLINE MotionData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void MotionData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MotionData::~MotionData() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.MotionData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MotionData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MotionData::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(MotionData, _impl_._cached_size_),
              false,
          },
          &MotionData::MergeImpl,
          &MotionData::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void MotionData::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.MotionData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MotionData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> MotionData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MotionData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::MotionData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MotionData, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(MotionData, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\7\0\0\0\0\0\0"
    "surrogate.grpc.MotionData"
    "message"
  }},
};

::uint8_t* MotionData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.MotionData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "surrogate.grpc.MotionData.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.MotionData)
  return target;
}

::size_t MotionData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.MotionData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MotionData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MotionData*>(&to_msg);
  auto& from = static_cast<const MotionData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.MotionData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MotionData::CopyFrom(const MotionData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.MotionData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MotionData::IsInitialized() const {
  return true;
}

void MotionData::InternalSwap(MotionData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata MotionData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fmotion_2eproto_getter,
                                   &descriptor_table_msgs_5fmotion_2eproto_once,
                                   file_level_metadata_msgs_5fmotion_2eproto[0]);
}
// ===================================================================

class MobileMotionData::_Internal {
 public:
};

MobileMotionData::MobileMotionData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.MobileMotionData)
}
MobileMotionData::MobileMotionData(
    ::google::protobuf::Arena* arena, const MobileMotionData& from)
    : MobileMotionData(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MobileMotionData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MobileMotionData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, system_state_),
           0,
           offsetof(Impl_, steering_pos_) -
               offsetof(Impl_, system_state_) +
               sizeof(Impl_::steering_pos_));
}
MobileMotionData::~MobileMotionData() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.MobileMotionData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MobileMotionData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MobileMotionData::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_._cached_size_),
              false,
          },
          &MobileMotionData::MergeImpl,
          &MobileMotionData::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void MobileMotionData::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.MobileMotionData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.system_state_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.steering_pos_) -
      reinterpret_cast<char*>(&_impl_.system_state_)) + sizeof(_impl_.steering_pos_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MobileMotionData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> MobileMotionData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MobileMotionData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::MobileMotionData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .surrogate.grpc.SystemState system_state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MobileMotionData, _impl_.system_state_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.system_state_)}},
    // float wheel_vel = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.wheel_vel_)}},
    // float steering_pos = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.steering_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.SystemState system_state = 1;
    {PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.system_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // float wheel_vel = 2;
    {PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.wheel_vel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float steering_pos = 3;
    {PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.steering_pos_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* MobileMotionData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.MobileMotionData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.SystemState system_state = 1;
  if (this->_internal_system_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_system_state(), target);
  }

  // float wheel_vel = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = this->_internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_wheel_vel(), target);
  }

  // float steering_pos = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = this->_internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_steering_pos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.MobileMotionData)
  return target;
}

::size_t MobileMotionData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.MobileMotionData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.SystemState system_state = 1;
  if (this->_internal_system_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_system_state());
  }

  // float wheel_vel = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = this->_internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    total_size += 5;
  }

  // float steering_pos = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = this->_internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MobileMotionData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MobileMotionData*>(&to_msg);
  auto& from = static_cast<const MobileMotionData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.MobileMotionData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_system_state() != 0) {
    _this->_impl_.system_state_ = from._impl_.system_state_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_wheel_vel = from._internal_wheel_vel();
  ::uint32_t raw_wheel_vel;
  memcpy(&raw_wheel_vel, &tmp_wheel_vel, sizeof(tmp_wheel_vel));
  if (raw_wheel_vel != 0) {
    _this->_impl_.wheel_vel_ = from._impl_.wheel_vel_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pos = from._internal_steering_pos();
  ::uint32_t raw_steering_pos;
  memcpy(&raw_steering_pos, &tmp_steering_pos, sizeof(tmp_steering_pos));
  if (raw_steering_pos != 0) {
    _this->_impl_.steering_pos_ = from._impl_.steering_pos_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MobileMotionData::CopyFrom(const MobileMotionData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.MobileMotionData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MobileMotionData::IsInitialized() const {
  return true;
}

void MobileMotionData::InternalSwap(MobileMotionData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.steering_pos_)
      + sizeof(MobileMotionData::_impl_.steering_pos_)
      - PROTOBUF_FIELD_OFFSET(MobileMotionData, _impl_.system_state_)>(
          reinterpret_cast<char*>(&_impl_.system_state_),
          reinterpret_cast<char*>(&other->_impl_.system_state_));
}

::google::protobuf::Metadata MobileMotionData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fmotion_2eproto_getter,
                                   &descriptor_table_msgs_5fmotion_2eproto_once,
                                   file_level_metadata_msgs_5fmotion_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_msgs_5fmotion_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
