// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_system.proto
// Protobuf C++ Version: 5.26.1

#include "msgs_system.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace surrogate {
namespace grpc {

inline constexpr SystemStateReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        system_state_{static_cast< ::surrogate::grpc::SystemState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SystemStateReply::SystemStateReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SystemStateReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SystemStateReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SystemStateReplyDefaultTypeInternal() {}
  union {
    SystemStateReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SystemStateReplyDefaultTypeInternal _SystemStateReply_default_instance_;

inline constexpr ChangeSystemStateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : command_id_{static_cast< ::surrogate::grpc::CommandId >(0)},
        system_state_{static_cast< ::surrogate::grpc::SystemState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChangeSystemStateRequest::ChangeSystemStateRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ChangeSystemStateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChangeSystemStateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChangeSystemStateRequestDefaultTypeInternal() {}
  union {
    ChangeSystemStateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChangeSystemStateRequestDefaultTypeInternal _ChangeSystemStateRequest_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fsystem_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msgs_5fsystem_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msgs_5fsystem_2eproto = nullptr;
const ::uint32_t
    TableStruct_msgs_5fsystem_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ChangeSystemStateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ChangeSystemStateRequest, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::ChangeSystemStateRequest, _impl_.system_state_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SystemStateReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SystemStateReply, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::surrogate::grpc::SystemStateReply, _impl_.system_state_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::surrogate::grpc::ChangeSystemStateRequest)},
        {10, -1, -1, sizeof(::surrogate::grpc::SystemStateReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::surrogate::grpc::_ChangeSystemStateRequest_default_instance_._instance,
    &::surrogate::grpc::_SystemStateReply_default_instance_._instance,
};
const char descriptor_table_protodef_msgs_5fsystem_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021msgs_system.proto\022\016surrogate.grpc\032\021msg"
    "s_common.proto\"|\n\030ChangeSystemStateReque"
    "st\022-\n\ncommand_id\030\001 \001(\0162\031.surrogate.grpc."
    "CommandId\0221\n\014system_state\030\002 \001(\0162\033.surrog"
    "ate.grpc.SystemState\"t\n\020SystemStateReply"
    "\022-\n\ncommand_id\030\001 \001(\0162\031.surrogate.grpc.Co"
    "mmandId\0221\n\014system_state\030\002 \001(\0162\033.surrogat"
    "e.grpc.SystemStateb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msgs_5fsystem_2eproto_deps[1] =
    {
        &::descriptor_table_msgs_5fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_msgs_5fsystem_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fsystem_2eproto = {
    false,
    false,
    306,
    descriptor_table_protodef_msgs_5fsystem_2eproto,
    "msgs_system.proto",
    &descriptor_table_msgs_5fsystem_2eproto_once,
    descriptor_table_msgs_5fsystem_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_msgs_5fsystem_2eproto::offsets,
    file_level_metadata_msgs_5fsystem_2eproto,
    file_level_enum_descriptors_msgs_5fsystem_2eproto,
    file_level_service_descriptors_msgs_5fsystem_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fsystem_2eproto_getter() {
  return &descriptor_table_msgs_5fsystem_2eproto;
}
namespace surrogate {
namespace grpc {
// ===================================================================

class ChangeSystemStateRequest::_Internal {
 public:
};

ChangeSystemStateRequest::ChangeSystemStateRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.ChangeSystemStateRequest)
}
ChangeSystemStateRequest::ChangeSystemStateRequest(
    ::google::protobuf::Arena* arena, const ChangeSystemStateRequest& from)
    : ChangeSystemStateRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ChangeSystemStateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ChangeSystemStateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           0,
           offsetof(Impl_, system_state_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::system_state_));
}
ChangeSystemStateRequest::~ChangeSystemStateRequest() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.ChangeSystemStateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ChangeSystemStateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ChangeSystemStateRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_._cached_size_),
              false,
          },
          &ChangeSystemStateRequest::MergeImpl,
          &ChangeSystemStateRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ChangeSystemStateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.ChangeSystemStateRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.system_state_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.system_state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ChangeSystemStateRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ChangeSystemStateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ChangeSystemStateRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::ChangeSystemStateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .surrogate.grpc.SystemState system_state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ChangeSystemStateRequest, _impl_.system_state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.system_state_)}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ChangeSystemStateRequest, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .surrogate.grpc.SystemState system_state = 2;
    {PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.system_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ChangeSystemStateRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.ChangeSystemStateRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // .surrogate.grpc.SystemState system_state = 2;
  if (this->_internal_system_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_system_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.ChangeSystemStateRequest)
  return target;
}

::size_t ChangeSystemStateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.ChangeSystemStateRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  // .surrogate.grpc.SystemState system_state = 2;
  if (this->_internal_system_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_system_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ChangeSystemStateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChangeSystemStateRequest*>(&to_msg);
  auto& from = static_cast<const ChangeSystemStateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.ChangeSystemStateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  if (from._internal_system_state() != 0) {
    _this->_impl_.system_state_ = from._impl_.system_state_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChangeSystemStateRequest::CopyFrom(const ChangeSystemStateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.ChangeSystemStateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ChangeSystemStateRequest::IsInitialized() const {
  return true;
}

void ChangeSystemStateRequest::InternalSwap(ChangeSystemStateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.system_state_)
      + sizeof(ChangeSystemStateRequest::_impl_.system_state_)
      - PROTOBUF_FIELD_OFFSET(ChangeSystemStateRequest, _impl_.command_id_)>(
          reinterpret_cast<char*>(&_impl_.command_id_),
          reinterpret_cast<char*>(&other->_impl_.command_id_));
}

::google::protobuf::Metadata ChangeSystemStateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fsystem_2eproto_getter,
                                   &descriptor_table_msgs_5fsystem_2eproto_once,
                                   file_level_metadata_msgs_5fsystem_2eproto[0]);
}
// ===================================================================

class SystemStateReply::_Internal {
 public:
};

SystemStateReply::SystemStateReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.SystemStateReply)
}
SystemStateReply::SystemStateReply(
    ::google::protobuf::Arena* arena, const SystemStateReply& from)
    : SystemStateReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SystemStateReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SystemStateReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           0,
           offsetof(Impl_, system_state_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::system_state_));
}
SystemStateReply::~SystemStateReply() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.SystemStateReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SystemStateReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SystemStateReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_._cached_size_),
              false,
          },
          &SystemStateReply::MergeImpl,
          &SystemStateReply::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void SystemStateReply::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.SystemStateReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.system_state_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.system_state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SystemStateReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SystemStateReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SystemStateReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::surrogate::grpc::SystemStateReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .surrogate.grpc.SystemState system_state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SystemStateReply, _impl_.system_state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.system_state_)}},
    // .surrogate.grpc.CommandId command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SystemStateReply, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.command_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .surrogate.grpc.CommandId command_id = 1;
    {PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .surrogate.grpc.SystemState system_state = 2;
    {PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.system_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* SystemStateReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.SystemStateReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command_id(), target);
  }

  // .surrogate.grpc.SystemState system_state = 2;
  if (this->_internal_system_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_system_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.SystemStateReply)
  return target;
}

::size_t SystemStateReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.SystemStateReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  // .surrogate.grpc.SystemState system_state = 2;
  if (this->_internal_system_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_system_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SystemStateReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SystemStateReply*>(&to_msg);
  auto& from = static_cast<const SystemStateReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.SystemStateReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  if (from._internal_system_state() != 0) {
    _this->_impl_.system_state_ = from._impl_.system_state_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SystemStateReply::CopyFrom(const SystemStateReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.SystemStateReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SystemStateReply::IsInitialized() const {
  return true;
}

void SystemStateReply::InternalSwap(SystemStateReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.system_state_)
      + sizeof(SystemStateReply::_impl_.system_state_)
      - PROTOBUF_FIELD_OFFSET(SystemStateReply, _impl_.command_id_)>(
          reinterpret_cast<char*>(&_impl_.command_id_),
          reinterpret_cast<char*>(&other->_impl_.command_id_));
}

::google::protobuf::Metadata SystemStateReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_msgs_5fsystem_2eproto_getter,
                                   &descriptor_table_msgs_5fsystem_2eproto_once,
                                   file_level_metadata_msgs_5fsystem_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_msgs_5fsystem_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
