// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system.proto

#include "system.pb.h"
#include "system.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace surrogate {
namespace grpc {

static const char* SystemService_method_names[] = {
  "/surrogate.grpc.SystemService/SystemEmergencyStop",
  "/surrogate.grpc.SystemService/SystemReset",
};

std::unique_ptr< SystemService::Stub> SystemService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SystemService::Stub> stub(new SystemService::Stub(channel, options));
  return stub;
}

SystemService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SystemEmergencyStop_(SystemService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SystemReset_(SystemService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SystemService::Stub::SystemEmergencyStop(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::surrogate::grpc::SystemStateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SystemEmergencyStop_, context, request, response);
}

void SystemService::Stub::async::SystemEmergencyStop(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemEmergencyStop_, context, request, response, std::move(f));
}

void SystemService::Stub::async::SystemEmergencyStop(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemEmergencyStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::SystemStateReply>* SystemService::Stub::PrepareAsyncSystemEmergencyStopRaw(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surrogate::grpc::SystemStateReply, ::surrogate::grpc::ChangeSystemStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SystemEmergencyStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::SystemStateReply>* SystemService::Stub::AsyncSystemEmergencyStopRaw(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSystemEmergencyStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SystemService::Stub::SystemReset(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::surrogate::grpc::SystemStateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SystemReset_, context, request, response);
}

void SystemService::Stub::async::SystemReset(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemReset_, context, request, response, std::move(f));
}

void SystemService::Stub::async::SystemReset(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemReset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::SystemStateReply>* SystemService::Stub::PrepareAsyncSystemResetRaw(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surrogate::grpc::SystemStateReply, ::surrogate::grpc::ChangeSystemStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SystemReset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surrogate::grpc::SystemStateReply>* SystemService::Stub::AsyncSystemResetRaw(::grpc::ClientContext* context, const ::surrogate::grpc::ChangeSystemStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSystemResetRaw(context, request, cq);
  result->StartCall();
  return result;
}

SystemService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SystemService::Service, ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SystemService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surrogate::grpc::ChangeSystemStateRequest* req,
             ::surrogate::grpc::SystemStateReply* resp) {
               return service->SystemEmergencyStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SystemService::Service, ::surrogate::grpc::ChangeSystemStateRequest, ::surrogate::grpc::SystemStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SystemService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surrogate::grpc::ChangeSystemStateRequest* req,
             ::surrogate::grpc::SystemStateReply* resp) {
               return service->SystemReset(ctx, req, resp);
             }, this)));
}

SystemService::Service::~Service() {
}

::grpc::Status SystemService::Service::SystemEmergencyStop(::grpc::ServerContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SystemService::Service::SystemReset(::grpc::ServerContext* context, const ::surrogate::grpc::ChangeSystemStateRequest* request, ::surrogate::grpc::SystemStateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace surrogate
}  // namespace grpc

